Blockly.defineBlocksWithJsonArray([{type:"neopixel_initialise",message0:"Init NeoPixel pin# %1 with %2 %3 neopixel[s]",args0:[{type:"input_value",name:"pin"},{type:"input_dummy"},{type:"field_number",name:"n",value:8,min:1}],previousStatement:null,nextStatement:null,colour:65,tooltip:"Make an object to control any attached neopixels. Specify the number of neopixels and the pin to which they are attached.",helpUrl:"https://microbit-micropython.readthedocs.io/en/latest/neopixel.html#neopixel.NeoPixel"},
{type:"neopixel_clear",message0:"Clear NeoPixels on pin# %1",args0:[{type:"input_value",name:"pin"}],previousStatement:null,nextStatement:null,colour:65,tooltip:"Clear all neopixels controlled by the referenced neopixel object.",helpUrl:"https://microbit-micropython.readthedocs.io/en/latest/neopixel.html#neopixel.NeoPixel.clear"},{type:"neopixel_show",message0:"Show NeoPixels on pin# %1",args0:[{type:"input_value",name:"pin"}],previousStatement:null,nextStatement:null,colour:65,tooltip:"Show / update all the neopixels controlled by the referenced neopixel object.",
helpUrl:"https://microbit-micropython.readthedocs.io/en/latest/neopixel.html#neopixel.NeoPixel.show"},{type:"neopixel_set",message0:"Using NeoPixels on pin# %1 set pixel in position %2 with red %3 green %4 blue %5",args0:[{type:"input_value",name:"pin"},{type:"input_value",name:"pixel",check:"Number"},{type:"input_value",name:"red",check:"Number"},{type:"input_value",name:"green",check:"Number"},{type:"input_value",name:"blue",check:"Number"}],inputsInline:!1,previousStatement:null,nextStatement:null,
colour:65,tooltip:"Use the referenced neopixel object to update the individual neopixel in a specific numbered position with a red, green, blue (RGB) value.",helpUrl:"https://microbit-micropython.readthedocs.io/en/latest/neopixel.html#using-neopixels"},{type:"neopixel_bounce",message0:"Show NeoPixels bounce effect on pin# %1 with red %2 green %3 blue %4 delay(ms) %5",args0:[{type:"input_value",name:"pin"},{type:"input_value",name:"red",check:"Number"},{type:"input_value",name:"green",check:"Number"},
{type:"input_value",name:"blue",check:"Number"},{type:"input_value",name:"delay",check:"Number"}],inputsInline:!1,previousStatement:null,nextStatement:null,colour:65,tooltip:"Show NeoPixels bounce effect .",helpUrl:"https://microbit-micropython.readthedocs.io/en/latest/neopixel.html#using-neopixels"},{type:"neopixel_cycle",message0:"Show NeoPixels cycle effect on pin# %1 with red %2 green %3 blue %4 delay(ms) %5",args0:[{type:"input_value",name:"pin"},{type:"input_value",name:"red",check:"Number"},
{type:"input_value",name:"green",check:"Number"},{type:"input_value",name:"blue",check:"Number"},{type:"input_value",name:"delay",check:"Number"}],inputsInline:!1,previousStatement:null,nextStatement:null,colour:65,tooltip:"Show NeoPixels cycle effect .",helpUrl:"https://microbit-micropython.readthedocs.io/en/latest/neopixel.html#using-neopixels"}]);Blockly.Msg.TYPE_CHECK="check type of";Blockly.Msg.DICT_KEYS="get all keys of ";Blockly.Msg.DICT_GET="Get value of key";Blockly.Msg.DICT_GET_TO="from";
Blockly.Msg.DICTS_CREATE_WITH_INPUT_WITH="Dict of";Blockly.Msg.DICTS_CREATE_WITH_TOOLTIP="Create a new dictionary";Blockly.Msg.DICTS_CREATE_EMPTY_TITLE="Create empty dict";Blockly.Msg.DICTS_CREATE_WITH_CONTAINER_TITLE_ADD="key-value pairs";Blockly.Msg.DICTS_CREATE_WITH_CONTAINER_TOOLTIP="**";Blockly.Msg.DICTS_CREATE_WITH_ITEM_TITLE="key-value";Blockly.Msg.DICTS_CREATE_WITH_ITEM_TOOLTIP="Make a new key-value pair";Blockly.Msg.DICTS_CREATE_WITH_ITEM_KEY="key";
Blockly.Msg.DICTS_CREATE_WITH_ITEM_VALUE="value";Blockly.Blocks.dicts_create_with_container={init:function(){this.setColour(280);this.appendDummyInput().appendField(Blockly.Msg.DICTS_CREATE_WITH_CONTAINER_TITLE_ADD);this.appendStatementInput("STACK");this.setTooltip(Blockly.Msg.DICTS_CREATE_WITH_CONTAINER_TOOLTIP);this.contextMenu=!1}};
Blockly.Blocks.dicts_create_with_item={init:function(){this.setColour(280);this.appendDummyInput().appendField(Blockly.Msg.DICTS_CREATE_WITH_ITEM_TITLE);this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip(Blockly.Msg.DICTS_CREATE_WITH_ITEM_TOOLTIP);this.contextMenu=!1}};
Blockly.Blocks.dicts_create_with={init:function(){this.setColour(280);this.appendDummyInput("TITLE_TEXT").appendField(Blockly.Msg.DICTS_CREATE_WITH_INPUT_WITH);this.appendValueInput("KEY0");this.appendValueInput("VALUE0");this.appendValueInput("KEY1");this.appendValueInput("VALUE1");this.setOutput(!0,"Dict");this.setMutator(new Blockly.Mutator(["dicts_create_with_item"]));this.setTooltip(Blockly.Msg.DICTS_CREATE_WITH_TOOLTIP);this.itemCount_=2},mutationToDom:function(a){a=document.createElement("mutation");
a.setAttribute("items",this.itemCount_);return a},domToMutation:function(a){this.removeInput("TITLE_TEXT");for(var b=0;b<this.itemCount_;b++)this.removeInput("KEY"+b),this.removeInput("VALUE"+b);this.itemCount_=parseInt(a.getAttribute("items"),10);this.appendDummyInput("TITLE_TEXT").appendField(Blockly.Msg.DICTS_CREATE_WITH_INPUT_WITH);for(b=0;b<this.itemCount_;b++)this.appendValueInput("KEY"+b).setCheck(null).appendField(Blockly.Msg.DICTS_CREATE_WITH_ITEM_KEY),this.appendValueInput("VALUE"+b).setCheck(null).appendField(Blockly.Msg.DICTS_CREATE_WITH_ITEM_VALUE)},
decompose:function(a){var b=a.newBlock("dicts_create_with_container");b.initSvg();for(var c=b.getInput("STACK").connection,e=0;e<this.itemCount_;e++){var d=a.newBlock("dicts_create_with_item");d.initSvg();c.connect(d.previousConnection);c=d.nextConnection}return b},compose:function(a){if(0==this.itemCount_)this.removeInput("EMPTY");else{this.removeInput("TITLE_TEXT");for(var b=this.itemCount_-1;0<=b;b--)this.removeInput("KEY"+b),this.removeInput("VALUE"+b)}this.itemCount_=0;a=a.getInputTargetBlock("STACK");
for(this.appendDummyInput("TITLE_TEXT").appendField(Blockly.Msg.DICTS_CREATE_WITH_INPUT_WITH);a;)this.appendValueInput("KEY"+this.itemCount_).appendField(Blockly.Msg.DICTS_CREATE_WITH_ITEM_KEY),b=this.appendValueInput("VALUE"+this.itemCount_).appendField(Blockly.Msg.DICTS_CREATE_WITH_ITEM_VALUE),a.valueConnection_&&b.connection.connect(a.valueConnection_),this.itemCount_++,a=a.nextConnection&&a.nextConnection.targetBlock();0==this.itemCount_&&this.appendDummyInput("EMPTY").appendField(Blockly.Msg.DICTS_CREATE_EMPTY_TITLE)},
saveConnections:function(a){a=a.getInputTargetBlock("STACK");for(var b=0;a;){this.getInput("KEY"+b);var c=this.getInput("VALUE"+b);a.valueConnection_=c&&c.connection.targetConnection;b++;a=a.nextConnection&&a.nextConnection.targetBlock()}}};Blockly.Blocks.dict_get={init:function(){this.setColour(280);this.appendValueInput("ITEM").appendField(Blockly.Msg.DICT_GET);this.appendValueInput("DICT").setCheck("Dict").appendField(Blockly.Msg.DICT_GET_TO);this.setInputsInline(!0);this.setOutput(!0)}};
Blockly.Blocks.deep_sleep8266={init:function(){this.appendValueInput("interval").setCheck("Number").appendField("Deep sleep");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(0);this.setTooltip("Deep sleep process in milliseconds");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.deep_sleep={init:function(){this.appendValueInput("interval").setCheck("Number").appendField("Deep sleep");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(0);this.setTooltip("Deep sleep process in milliseconds");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.delay={init:function(){this.appendValueInput("time").setCheck("Number").appendField("Delay seconds");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(140);this.setTooltip("Delay processing in seconds");this.setHelpUrl("http://www.bipes.net.br/")}};
Blockly.Blocks.delay_ms={init:function(){this.appendValueInput("time").setCheck("Number").appendField("Delay milliseconds");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(140);this.setTooltip("Delay processing in milliseconds");this.setHelpUrl("http://www.bipes.net.br/")}};
Blockly.Blocks.delay_us={init:function(){this.appendValueInput("time").setCheck("Number").appendField("Delay microseconds");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(140);this.setTooltip("Delay processing in microseconds");this.setHelpUrl("http://www.bipes.net.br/")}};
Blockly.Blocks.ticks_ms={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Get milliseconds counter"),"MSG_GET_MS");this.setOutput(!0,null);this.setColour(140);this.setTooltip("Get millisecond counter");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.ticks_diff={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Compute time difference"),"DIFF_TS");this.setOutput(!0,null);this.appendValueInput("end").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("end");this.appendValueInput("start").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("start");this.setColour(140);this.setTooltip("Compute time difference");this.setHelpUrl("bipes.net.br")}};
Blockly.Blocks.set_rtc={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Set RTC value"),"SET_RTC");this.appendValueInput("year").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("year");this.appendValueInput("month").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("month");this.appendValueInput("day").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("day");this.appendValueInput("hour").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("hour");
this.appendValueInput("minute").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("minute");this.appendValueInput("second").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("second");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(140);this.setTooltip("Set RTC value");this.setHelpUrl("bipes.net.br")}};
Blockly.Blocks.get_rtc={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Get RTC value"),"MSG_GET_RTC");this.setOutput(!0,null);this.setColour(140);this.setTooltip("Get RTC value");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.get_rtc_datetime={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Get RTC datetime"),"GET_RTC_DATETIME");this.appendValueInput("year").setCheck("Variable").setAlign(Blockly.ALIGN_RIGHT).appendField("year var");this.appendValueInput("month").setCheck("Variable").setAlign(Blockly.ALIGN_RIGHT).appendField("month var");this.appendValueInput("day").setCheck("Variable").setAlign(Blockly.ALIGN_RIGHT).appendField("day var");this.appendValueInput("hour").setCheck("Variable").setAlign(Blockly.ALIGN_RIGHT).appendField("hour var");
this.appendValueInput("minute").setCheck("Variable").setAlign(Blockly.ALIGN_RIGHT).appendField("minute var");this.appendValueInput("second").setCheck("Variable").setAlign(Blockly.ALIGN_RIGHT).appendField("second var");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(140);this.setTooltip("Get RTC datetime");this.setHelpUrl("bipes.net.br")}};
Blockly.Blocks.timer={init:function(){this.setColour(140);this.appendDummyInput().appendField("Timer # ").appendField(new Blockly.FieldTextInput("0"),"timerNumber").appendField(" Interval (ms): ").appendField(new Blockly.FieldTextInput("1000"),"interval");this.appendStatementInput("statements").setCheck("image");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.stop_timer={init:function(){this.appendValueInput("timerNumber").setCheck("Number").appendField("Stop Timer");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(140);this.setTooltip("Stop Timer");this.setHelpUrl("www.bipes.net.br")}};Blockly.Blocks.reset={init:function(){this.appendDummyInput().appendField("reset");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(0);this.setTooltip("Reset Device");this.setHelpUrl("www.bipes.net.br")}};
Blockly.Blocks.soft_reset={init:function(){this.appendDummyInput().appendField("soft reset");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(0);this.setTooltip("Soft reset Device");this.setHelpUrl("www.bipes.net.br")}};Blockly.Blocks.reset_cause_soft={init:function(){this.appendDummyInput().appendField("Cause: soft reset");this.setOutput(!0,null);this.setColour(0);this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.reset_cause_hard={init:function(){this.appendDummyInput().appendField("Cause: hard reset");this.setOutput(!0,null);this.setColour(0);this.setHelpUrl("http://www.bipes.net.br")}};Blockly.Blocks.reset_cause_wdt={init:function(){this.appendDummyInput().appendField("Cause: reset by watchdog timer");this.setOutput(!0,null);this.setColour(0);this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.reset_cause_deep={init:function(){this.appendDummyInput().appendField("Cause: woke up from deepsleep");this.setOutput(!0,null);this.setColour(0);this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.exec_python={init:function(){this.appendDummyInput().appendField(new Blockly.FieldImage("media/600px-Python-logo-notext.svg.png",55,55,"*")).appendField("Execute custom Python code");this.appendValueInput("command").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("statement");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(100);this.setTooltip("Execute custom Python Code");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.exec_import_python_module={init:function(){this.appendValueInput("command").setCheck("String").appendField("Import custom Python Module");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(100);this.setTooltip("Import Python Module");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.set_freq={init:function(){this.appendDummyInput().appendField("Set CPU clock frequency");this.appendValueInput("freq").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("frequency (Hz)");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setColour(0);this.setTooltip("Set ESP8266 CPU Clock Frequency");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.get_freq={init:function(){this.appendDummyInput().appendField("Get CPU clock frequency");this.setOutput(!0,null);this.setColour(0);this.setTooltip("Get current CPU Clock Frequency");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.gpio_set={update_list:function(){document.getElementById("device_selector").value in pinout?this.options=pinout[document.getElementById("device_selector").value]:this.options=[["Pins are not defined","None"]]},options:[],init:function(){this.update_list();this.appendDummyInput().appendField("Set digital output pin#").appendField(new Blockly.FieldDropdown(this.options),"PIN");this.appendValueInput("value").setCheck(null).setAlign(Blockly.ALIGN_RIGHT).appendField("to");this.setPreviousStatement(!0,
null);this.setNextStatement(!0,null);this.setColour(245);this.setTooltip("Write to GPIO digital output pin");this.setHelpUrl("bipes.net.br")}};
Blockly.Blocks.gpio_set_mehtod_chaining={init:function(){this.appendValueInput("pin").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("Set digital output pin#");this.appendValueInput("value").setCheck(null).setAlign(Blockly.ALIGN_RIGHT).appendField("to");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(245);this.setTooltip("Use mehtod chaining Write to GPIO digital output pin");this.setHelpUrl("bipes.net.br")}};
Blockly.Blocks.gpio_get={update_list:function(){document.getElementById("device_selector").value in pinout?this.options=pinout[document.getElementById("device_selector").value]:this.options=[["Pins are not defined","None"]]},options:[],init:function(){this.update_list();this.appendDummyInput().appendField("Read digital input pin#").appendField(new Blockly.FieldDropdown(this.options),"PIN");this.setOutput(!0,null);this.setColour(245);this.setTooltip("Read digital input pin");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.gpio_get_out={update_list:function(){document.getElementById("device_selector").value in pinout?this.options=pinout[document.getElementById("device_selector").value]:this.options=[["Pins are not defined","None"]]},options:[],init:function(){this.update_list();this.appendDummyInput().appendField("Read digital output pin#").appendField(new Blockly.FieldDropdown(this.options),"PIN");this.setOutput(!0,null);this.setColour(245);this.setTooltip("Read digital output pin");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.adc={init:function(){this.appendValueInput("pin").setCheck("Number").appendField("Read analog input adc#");this.setOutput(!0,null);this.setColour(245);this.setTooltip("Read ADC input of specified pin");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.pinout={update_list:function(){document.getElementById("device_selector").value in pinout?this.options=pinout[document.getElementById("device_selector").value]:this.options=[["Pins are not defined","None"]]},options:[],init:function(){this.update_list();this.appendDummyInput().appendField("pin").appendField(new Blockly.FieldDropdown(this.options),"PIN");this.setOutput(!0,null);this.setColour(245);this.setTooltip("Pins");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.pwm={update_list:function(){document.getElementById("device_selector").value in pinout?this.options=pinout[document.getElementById("device_selector").value]:this.options=[["Pins are not defined","None"]]},options:[],init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Set analog output : PWM"),"MSG_GET_MS");this.update_list();this.appendDummyInput().appendField("pin#").appendField(new Blockly.FieldDropdown(this.options),"PIN").setAlign(Blockly.ALIGN_RIGHT);
this.appendValueInput("frequency").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("frequency");this.appendValueInput("duty").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("duty");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(245);this.setTooltip("pwm");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.pwm_duty={update_list:function(){document.getElementById("device_selector").value in pinout?this.options=pinout[document.getElementById("device_selector").value]:this.options=[["Pins are not defined","None"]]},options:[],init:function(){this.update_list();this.appendDummyInput().appendField("Reset PWM duty pin#").appendField(new Blockly.FieldDropdown(this.options),"PIN");this.appendValueInput("duty").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("duty");this.setPreviousStatement(!0,
null);this.setNextStatement(!0,null);this.setColour(245);this.setTooltip("Set PWM duty");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.gpio_create_pinobj={update_list:function(){document.getElementById("device_selector").value in pinout?this.options=pinout[document.getElementById("device_selector").value]:this.options=[["Pins are not defined","None"]]},options:[],init:function(){this.update_list();this.appendDummyInput().appendField("Create Pin obj pin#").appendField(new Blockly.FieldDropdown(this.options),"PIN");this.setOutput(!0,null);this.setColour(245);this.setTooltip("Create Pin Object");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.gpio_set_pinobj={init:function(){this.appendValueInput("obj").setCheck("Variable").setAlign(Blockly.ALIGN_RIGHT).appendField("Set digital output pin obj");this.appendValueInput("value").setCheck(null).setAlign(Blockly.ALIGN_RIGHT).appendField("to");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(245);this.setTooltip("Write to GPIO digital output pin");this.setHelpUrl("bipes.net.br")}};
Blockly.Blocks.gpio_create_pwmobj={update_list:function(){document.getElementById("device_selector").value in pinout?this.options=pinout[document.getElementById("device_selector").value]:this.options=[["Pins are not defined","None"]]},options:[],init:function(){this.appendDummyInput().appendField("Create PWM object");this.update_list();this.appendDummyInput().appendField("pin#").appendField(new Blockly.FieldDropdown(this.options),"PIN").setAlign(Blockly.ALIGN_RIGHT);this.appendValueInput("frequency").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("frequency");
this.appendValueInput("duty").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("duty");this.setOutput(!0,null);this.setColour(245);this.setTooltip("Create PWM Object");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.gpio_pwmobj_duty={init:function(){this.appendValueInput("obj").setCheck("Variable").setAlign(Blockly.ALIGN_RIGHT).appendField("Reset PWM duty pwm obj");this.appendValueInput("duty").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("duty");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(245);this.setTooltip("Set PWM obj duty");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.onewire_ds18x20_init={init:function(){this.setColour(45);this.appendDummyInput().appendField("Init OneWire Bus");this.appendValueInput("pin").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("pin#");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};Blockly.Blocks.onewire_ds18x20_scan={init:function(){this.setColour(45);this.appendDummyInput().appendField("Scan DS1820 sensors");this.setOutput(!0,null);this.setTooltip("")}};
Blockly.Blocks.onewire_ds18x20_convert={init:function(){this.setColour(45);this.appendDummyInput().appendField("Trigger DS1820 reading");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};Blockly.Blocks.onewire_ds18x20_read_temp={init:function(){this.setColour(45);this.appendDummyInput().appendField("DS1820 Temperature reading");this.appendValueInput("item").setAlign(Blockly.ALIGN_RIGHT).appendField("item");this.setOutput(!0,null);this.setTooltip("")}};
Blockly.Blocks.init_mpu6050={init:function(){this.setColour(35);this.appendDummyInput().appendField("Init I2C MPU6050 IMU");this.appendDummyInput().appendField(new Blockly.FieldImage("media/mpu6050.png",55,55,"*"));this.appendDummyInput().setAlign(Blockly.ALIGN_RIGHT).appendField("SDA#: GPIO4");this.appendDummyInput().setAlign(Blockly.ALIGN_RIGHT).appendField("SCL#: GPIO5");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.mpu6050_read_acc_x={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Acceleration - X axis"),"MSG_READ_MPU6050");this.setOutput(!0,null);this.setColour(35);this.setTooltip("Acceleration on X axis");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.mpu6050_read_acc_y={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Acceleration - Y axis"),"MSG_READ_MPU6050");this.setOutput(!0,null);this.setColour(35);this.setTooltip("Acceleration on Y axis");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.mpu6050_read_acc_z={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Acceleration - Z axis"),"MSG_READ_MPU6050");this.setOutput(!0,null);this.setColour(35);this.setTooltip("Acceleration on Z axis");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.mpu6050_read_gyro_x={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Gyro - X axis"),"MSG_READ_MPU6050");this.setOutput(!0,null);this.setColour(35);this.setTooltip("Gyro on X axis");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.mpu6050_read_gyro_y={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Gyro - Y axis"),"MSG_READ_MPU6050");this.setOutput(!0,null);this.setColour(35);this.setTooltip("Gyro on Y axis");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.mpu6050_read_gyro_z={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Gyro - Z axis"),"MSG_READ_MPU6050");this.setOutput(!0,null);this.setColour(35);this.setTooltip("Gyro on Z axis");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.init_oled={init:function(){this.setColour(185);this.appendDummyInput().appendField("Init I2C SSD1306 OLED display");this.appendDummyInput().appendField(new Blockly.FieldImage("media/oled.png",55,55,"*"));this.appendValueInput("sda").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("SDA#");this.appendValueInput("scl").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("SCL#");this.appendValueInput("width").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("width");
this.appendValueInput("height").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("height");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};Blockly.Blocks.power_oled={init:function(){this.setColour(185);this.appendDummyInput().appendField("OLED power");this.appendValueInput("state").setCheck(null).setAlign(Blockly.ALIGN_RIGHT).appendField("ON/OFF");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.fill_oled={init:function(){this.appendValueInput("value").setCheck("Number").appendField("Fill OLED display with ");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(185);this.setTooltip("Fill OLED Disiplay");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.clear_oled={init:function(){this.appendDummyInput().appendField("Clear OLED display");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(185);this.setTooltip("Clear OLED Disiplay");this.setHelpUrl("http://www.bipes.net.br")}};Blockly.Blocks.show_oled={init:function(){this.appendDummyInput().appendField("Show OLED display");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(185);this.setTooltip("Show OLED Disiplay");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.write_oled={init:function(){this.appendDummyInput().appendField("Write text on display");this.appendValueInput("x").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("x position");this.appendValueInput("y").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("y position");this.appendValueInput("text").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("text");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(185);this.setTooltip("Write text to OLED Display");
this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.max7219_init={init:function(){this.appendDummyInput().appendField(new Blockly.FieldImage("media/max7219.png",55,55,"*")).appendField("Init MAX7219 LED Matrix");this.appendValueInput("din").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("DIN#");this.appendValueInput("cs").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("CS#");this.appendValueInput("clk").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("CLK#");this.appendValueInput("num").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("number of modules");
this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(195);this.setTooltip("Init MX7219 LED Matrix");this.setHelpUrl("http://www.bipes.net.br")}};Blockly.Blocks.max7219_brightness={init:function(){this.appendValueInput("value").setCheck("Number").appendField("LED Matrix brightness(0~15) ");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(195);this.setTooltip("LED Matrix brightness");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.max7219_clear={init:function(){this.appendDummyInput().appendField("Clear LED Matrix");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(195);this.setTooltip("Clear LED Matrix Disiplay");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.max7219_write={init:function(){this.appendDummyInput().appendField("Write text on LED Matrix");this.appendValueInput("text").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("text");this.appendValueInput("x").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("x position");this.appendValueInput("y").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("y position");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(195);this.setTooltip("Write text to LED Matrix");
this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.max7219_scroll={init:function(){this.appendDummyInput().appendField("Scroll text on LED Matrix");this.appendValueInput("text").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("text");this.appendValueInput("delayms").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("scroll delay(ms)");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(195);this.setTooltip("Scroll text to LED Matrix");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.max7219_show={init:function(){this.appendDummyInput().appendField("Show LED Matrix");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(195);this.setTooltip("Show LED Matrix");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.init_servo={init:function(){this.appendDummyInput().appendField(new Blockly.FieldImage("media/servo.png",55,55,"*")).appendField("Init RC servo motor");this.appendValueInput("pin").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("pin#");this.setColour(85);this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setTooltip("Init RC servo motor");this.setHelpUrl("http://www.bipes.net.ebr")}};
Blockly.Blocks.move_servo={init:function(){this.appendDummyInput().appendField("Move servo motor");this.appendValueInput("pin").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("pin#");this.appendValueInput("angle").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("angle");this.setColour(85);this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setTooltip("Move RC servo motor to degrees");this.setHelpUrl("http://www.bipes.net.ebr")}};
Blockly.Blocks.net_get_request={init:function(){this.appendValueInput("URL").setCheck("String").appendField(new Blockly.FieldLabelSerializable("Make HTTP GET Request URL"),"BLOCK_NET_GET");this.setOutput(!0,"Response");this.setColour(250);this.setTooltip("Make HTTP GET Request");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.net_response_statuscode={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Get status code"),"BLOCK_NET_STATUSCODE");this.setOutput(!0,null);this.appendValueInput("response").setCheck("Response").setAlign(Blockly.ALIGN_RIGHT).appendField("response");this.setColour(250);this.setTooltip("Get Response Status Code");this.setHelpUrl("bipes.net.br")}};
Blockly.Blocks.net_response_text={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Get text"),"BLOCK_NET_TEXT");this.setOutput(!0,null);this.appendValueInput("response").setCheck("Response").setAlign(Blockly.ALIGN_RIGHT).appendField("response");this.setColour(250);this.setTooltip("Get Response Text");this.setHelpUrl("bipes.net.br")}};
Blockly.Blocks.net_response_encoding={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Get encoding"),"BLOCK_NET_ENCODING");this.setOutput(!0,null);this.appendValueInput("response").setCheck("Response").setAlign(Blockly.ALIGN_RIGHT).appendField("response");this.setColour(250);this.setTooltip("Get Response Encoding");this.setHelpUrl("bipes.net.br")}};
Blockly.Blocks.net_response_json={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Get JSON"),"BLOCK_NET_JSON");this.setOutput(!0,"JSON");this.appendValueInput("response").setCheck("Response").setAlign(Blockly.ALIGN_RIGHT).appendField("response");this.setColour(250);this.setTooltip("Get Response JSON");this.setHelpUrl("bipes.net.br")}};
Blockly.Blocks.net_response_json_get={init:function(){this.setColour(250);this.appendValueInput("item").appendField("Get JSON item");this.appendValueInput("json").setCheck("JSON").appendField("from");this.setInputsInline(!0);this.setOutput(!0)}};
Blockly.Blocks.net_post_request={init:function(){this.appendValueInput("URL").setCheck("String").appendField(new Blockly.FieldLabelSerializable("Make HTTP POST Request URL"),"NET_POST_REQUEST_URL");this.appendValueInput("data").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("data"),"NET_POST_REQUEST_DATA");this.setOutput(!0,null);this.setColour(250);this.setTooltip("Make HTTP POST Request");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.net_get_request_params={init:function(){this.appendValueInput("URL").setCheck("String").appendField(new Blockly.FieldLabelSerializable("Make xrequests GET Request URL"),"NET_POST_REQUEST_URL3");this.appendValueInput("params").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("params"),"NET_POST_REQUEST_PARAMS");this.setOutput(!0,null);this.setColour(80);this.setTooltip("USE xrequests.py Make HTTP GET Request");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.net_post_request_header={init:function(){this.appendValueInput("URL").setCheck("String").appendField(new Blockly.FieldLabelSerializable("Make xrequests POST request URL"),"NET_POST_REQUEST_URL2");this.setOutput(!0,null);this.appendValueInput("data").setAlign(Blockly.ALIGN_RIGHT).appendField("data");this.appendValueInput("header").setAlign(Blockly.ALIGN_RIGHT).appendField("header");this.setOutput(!0,null);this.setColour(80);this.setTooltip("USE xrequests.py Make HTTP POST Request");
this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.net_post_request_json={init:function(){this.appendValueInput("URL").setCheck("String").appendField(new Blockly.FieldLabelSerializable("Make xrequests POST request URL"),"NET_POST_REQUEST_URL4");this.setOutput(!0,null);this.appendValueInput("data").setAlign(Blockly.ALIGN_RIGHT).appendField("data");this.appendValueInput("json").setAlign(Blockly.ALIGN_RIGHT).appendField("json");this.appendValueInput("header").setAlign(Blockly.ALIGN_RIGHT).appendField("header");this.setOutput(!0,null);
this.setColour(80);this.setTooltip("USE xrequests.py Make HTTP POST Request");this.setHelpUrl("http://www.bipes.net.br")}};Blockly.Blocks.net_ifconfig={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Wifi current IP"),"NET_IFCONFIG");this.setOutput(!0,null);this.setColour(220);this.setTooltip("Wifi current IP");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.net_isconnected={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Wifi is connected?"),"NET_ISCONNECTED");this.setOutput(!0,null);this.setColour(220);this.setTooltip("Wifi is connected?");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.net_disconnect={init:function(){this.appendDummyInput().appendField("Disconnect Wifi");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(220);this.setTooltip("Disconnect from the currently connected wireless network");this.setHelpUrl("www.bipes.net.br")}};
Blockly.Blocks.exec_python_output={init:function(){this.appendValueInput("command").setCheck("String").appendField(new Blockly.FieldLabelSerializable("Set custom Python value"),"EXEC_PYTHON_OUTPUT");this.setOutput(!0,null);this.setColour(100);this.setTooltip("Set custom Python value");this.setHelpUrl("")}};
Blockly.Blocks.exec_python_func={init:function(){this.appendValueInput("command").setCheck("String").appendField(new Blockly.FieldLabelSerializable("Call custom Python func"),"EXEC_PYTHON_FUNC");this.setOutput(!0,null);this.setColour(100);this.setTooltip("Call custom Python func");this.setHelpUrl("")}};
Blockly.Blocks.net_ap_mode={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Configure Access Point Mode"),"NAME");this.appendValueInput("wifi_essid").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("Network name"),"NET_NETWORK_NAME");this.appendValueInput("wifi_key").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("Network password"),"NET_NETWORK_KEY");this.setPreviousStatement(!0,
null);this.setNextStatement(!0,null);this.setColour(220);this.setTooltip("Configure Access Point Mode");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.wifi_client_connect={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Connect to Wifi network"),"NAME");this.appendValueInput("wifi_client_essid").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("Network name"),"WIFI_CLIENT_NET_NAME");this.appendValueInput("wifi_client_key").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("Network key"),"WIFI_CLIENT_NET_KEY");
this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(220);this.setTooltip("Connect to a Wifi network");this.setHelpUrl("http://www.bipes.net.br")}};Blockly.Blocks.wifi_client_scan_networks={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Scan Wifi networks"),"NET_SCAN_WIFI");this.setOutput(!0,null);this.setColour(220);this.setTooltip("Scan wifi networks");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.tm1640_init={init:function(){this.appendDummyInput().appendField(new Blockly.FieldImage("media/matrix.png",55,55,"*")).appendField("Start TM1640 LED Matrix");this.appendValueInput("clk").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("CLK");this.appendValueInput("dio").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("DIO");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(230);this.setTooltip("Start TM1640 LED Matrix");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.tm1640_write={init:function(){this.appendDummyInput().appendField("Write array to Led Matrix");this.appendValueInput("vector").setCheck("String").appendField("LED array value");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(230);this.setTooltip("Write to TM1640 LED Matrix");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.tm1640_num={init:function(){this.appendDummyInput().appendField("Write Number on Led Matrix");this.appendValueInput("num").setCheck("Number").appendField("value (0-9)");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(230);this.setTooltip("Write number on TM1640 LED Matrix");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.tm1640_brig={init:function(){this.appendDummyInput().appendField("Set Brightness of Led Matrix");this.appendValueInput("brig").setCheck("Number").appendField("value (1-7)");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(230);this.setTooltip("Set brightness of TM1640 LED Matrix");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.tm1640_custom={init:function(){this.appendDummyInput().appendField("Custom Data Matrix layout");this.appendDummyInput().appendField(new Blockly.FieldCheckbox(!0,null,{checkCharacter:"\u2713"}),"A0").appendField(new Blockly.FieldCheckbox(!0,null,{checkCharacter:"\u2713"}),"A1").appendField(new Blockly.FieldCheckbox(!0,null,{checkCharacter:"\u2713"}),"A2").appendField(new Blockly.FieldCheckbox(!0,null,{checkCharacter:"\u2713"}),"A3").appendField(new Blockly.FieldCheckbox(!0,null,{checkCharacter:"\u2713"}),
"A4").appendField(new Blockly.FieldCheckbox(!0,null,{checkCharacter:"\u2713"}),"A5").appendField(new Blockly.FieldCheckbox(!0,null,{checkCharacter:"\u2713"}),"A6").appendField(new Blockly.FieldCheckbox(!0,null,{checkCharacter:"\u2713"}),"A7");this.appendDummyInput().appendField(new Blockly.FieldCheckbox("TRUE"),"B0").appendField(new Blockly.FieldCheckbox("TRUE"),"B1").appendField(new Blockly.FieldCheckbox("TRUE"),"B2").appendField(new Blockly.FieldCheckbox("TRUE"),"B3").appendField(new Blockly.FieldCheckbox("TRUE"),
"B4").appendField(new Blockly.FieldCheckbox("TRUE"),"B5").appendField(new Blockly.FieldCheckbox("TRUE"),"B6").appendField(new Blockly.FieldCheckbox("TRUE"),"B7");this.appendDummyInput().appendField(new Blockly.FieldCheckbox("TRUE"),"C0").appendField(new Blockly.FieldCheckbox("TRUE"),"C1").appendField(new Blockly.FieldCheckbox("TRUE"),"C2").appendField(new Blockly.FieldCheckbox("TRUE"),"C3").appendField(new Blockly.FieldCheckbox("TRUE"),"C4").appendField(new Blockly.FieldCheckbox("TRUE"),"C5").appendField(new Blockly.FieldCheckbox("TRUE"),
"C6").appendField(new Blockly.FieldCheckbox("TRUE"),"C7");this.appendDummyInput().appendField(new Blockly.FieldCheckbox("TRUE"),"D0").appendField(new Blockly.FieldCheckbox("TRUE"),"D1").appendField(new Blockly.FieldCheckbox("TRUE"),"D2").appendField(new Blockly.FieldCheckbox("TRUE"),"D3").appendField(new Blockly.FieldCheckbox("TRUE"),"D4").appendField(new Blockly.FieldCheckbox("TRUE"),"D5").appendField(new Blockly.FieldCheckbox("TRUE"),"D6").appendField(new Blockly.FieldCheckbox("TRUE"),"D7");this.appendDummyInput().appendField(new Blockly.FieldCheckbox("TRUE"),
"E0").appendField(new Blockly.FieldCheckbox("TRUE"),"E1").appendField(new Blockly.FieldCheckbox("TRUE"),"E2").appendField(new Blockly.FieldCheckbox("TRUE"),"E3").appendField(new Blockly.FieldCheckbox("TRUE"),"E4").appendField(new Blockly.FieldCheckbox("TRUE"),"E5").appendField(new Blockly.FieldCheckbox("TRUE"),"E6").appendField(new Blockly.FieldCheckbox("TRUE"),"E7");this.appendDummyInput().appendField(new Blockly.FieldCheckbox("TRUE"),"F0").appendField(new Blockly.FieldCheckbox("TRUE"),"F1").appendField(new Blockly.FieldCheckbox("TRUE"),
"F2").appendField(new Blockly.FieldCheckbox("TRUE"),"F3").appendField(new Blockly.FieldCheckbox("TRUE"),"F4").appendField(new Blockly.FieldCheckbox("TRUE"),"F5").appendField(new Blockly.FieldCheckbox("TRUE"),"F6").appendField(new Blockly.FieldCheckbox("TRUE"),"F7");this.appendDummyInput().appendField(new Blockly.FieldCheckbox("TRUE"),"G0").appendField(new Blockly.FieldCheckbox("TRUE"),"G1").appendField(new Blockly.FieldCheckbox("TRUE"),"G2").appendField(new Blockly.FieldCheckbox("TRUE"),"G3").appendField(new Blockly.FieldCheckbox("TRUE"),
"G4").appendField(new Blockly.FieldCheckbox("TRUE"),"G5").appendField(new Blockly.FieldCheckbox("TRUE"),"G6").appendField(new Blockly.FieldCheckbox("TRUE"),"G7");this.appendDummyInput().appendField(new Blockly.FieldCheckbox("TRUE"),"H0").appendField(new Blockly.FieldCheckbox("TRUE"),"H1").appendField(new Blockly.FieldCheckbox("TRUE"),"H2").appendField(new Blockly.FieldCheckbox("TRUE"),"H3").appendField(new Blockly.FieldCheckbox("TRUE"),"H4").appendField(new Blockly.FieldCheckbox("TRUE"),"H5").appendField(new Blockly.FieldCheckbox("TRUE"),
"H6").appendField(new Blockly.FieldCheckbox("TRUE"),"H7");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(230);this.setTooltip("Write to LED Matrix");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.file_open_write={init:function(){this.appendDummyInput().appendField("Open text file for writing");this.appendValueInput("filename").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("filename");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(205);this.setTooltip("Open text file for writing on the filesystem");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.file_open_read={init:function(){this.appendDummyInput().appendField("Open text file for reading");this.appendValueInput("filename").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("filename");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(205);this.setTooltip("Open text file for reading on the filesystem");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.file_close={init:function(){this.appendDummyInput().appendField("Close file");this.appendValueInput("filename").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("filename");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(205);this.setTooltip("Safely close file");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.file_write={init:function(){this.appendDummyInput().appendField("Write text to file");this.appendValueInput("filename").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("filename");this.appendValueInput("data").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("data");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(205);this.setTooltip("Write string to file");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.file_read={init:function(){this.appendDummyInput().appendField("Read text from the file");this.appendValueInput("filename").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("filename");this.setOutput(!0,null);this.setColour(205);this.setTooltip("Read string from a file");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.files_list={init:function(){this.appendDummyInput().appendField("List files");this.setOutput(!0,null);this.setColour(205);this.setTooltip("List files from current directory ");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.hcsr_init={init:function(){this.appendDummyInput().appendField(new Blockly.FieldImage("media/hcsr04.png",55,55,"*")).appendField("Init HC-SR04 Ultrasound sensor");this.appendValueInput("echo").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("echo pin#"),"HCSR_ECHOPIN_MSG");this.appendValueInput("trigger").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("trigger pin#"),"HCSR_TRIGPIN_MSG");
this.appendValueInput("timeout").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("timeout(us)"),"HCSR_TIMEOUT_MSG");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(25);this.setTooltip("Start HC-SR04 ultrasound distance sensor");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.hcsr_read={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Get distance (ultrasound sensor)"),"MSG_READ_DHT_TEMP");this.setOutput(!0,null);this.setColour(25);this.setTooltip("Measure distance with ultrasound sensor");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.dht_init={init:function(){this.appendDummyInput().appendField(new Blockly.FieldImage("media/dht.png",55,55,"*")).appendField("Init DHT Sensor");this.appendDummyInput().appendField("Type").appendField(new Blockly.FieldDropdown([["DHT11","DHT11"],["DHT22","DHT22"]]),"DHT_TYPE");this.appendValueInput("pin").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("pin#"),"DHT_PIN_MSG");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);
this.setColour(15);this.setTooltip("Init DHT11 ou DHT22 sensor");this.setHelpUrl("http://www.bipes.net.br")}};Blockly.Blocks.dht_measure={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Measure DHT11/22 Sensor"),"MSG_MEASURE_DHT");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(15);this.setTooltip("Measure DHT11/22 Sensor");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.dht_read_temp={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Read DHT11/22 Temperature"),"MSG_READ_DHT_TEMP");this.setOutput(!0,null);this.setColour(15);this.setTooltip("Read DHT11/22 Temperature");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.dht_read_humidity={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Read DHT11/22 Humidity"),"MSG_READ_DHT_HUMI");this.setOutput(!0,null);this.setColour(15);this.setTooltip("Read DHT11/22 Humidity");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.mqtt_init={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Init MQTT client"),"BLOCK_MQTT_INIT");this.appendValueInput("clientid").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("client ID"),"MQTT_CLIENT_ID");this.appendValueInput("server").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("server address"),"MQTT_SERVER");this.appendValueInput("port").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("server port"),
"MQTT_PORT");this.appendValueInput("user").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("username"),"MQTT_USER");this.appendValueInput("password").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("password"),"MQTT_PASSWORD");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(280);this.setTooltip("Init MQTT Client");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.mqtt_add_to_buffer={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Add data to MQTT buffer"),"BLOCK_MQTT_ADD_TO_BUFFER");this.appendValueInput("fieldname").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("field name"),"MQTT_FIELDNAME");this.appendValueInput("value").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("value"),"MQTT_VALUE");this.setPreviousStatement(!0,null);
this.setNextStatement(!0,null);this.setColour(280);this.setTooltip("Add Data to MQTT Buffer");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.mqtt_publish_buffer={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Publish buffer to MQTT topic"),"BLOCK_MQTT_PUBLISH");this.appendValueInput("topic").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("topic"),"MQTT_TOPIC");this.appendDummyInput().appendField("QOS:").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldDropdown([["0 - at most\u00a0once","0"],["1 - at least\u00a0once","1"],
["2 - exactly\u00a0once","2"]]),"MQTT_QOS");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(280);this.setInputsInline(!1);this.setTooltip("Publish Buffer to MQTT Server");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.mqtt_publish_payload={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Publish payload to MQTT topic"),"BLOCK_MQTT_PUBLISH");this.appendValueInput("topic").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("topic"),"MQTT_TOPIC");this.appendValueInput("payload").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("payload"),"MQTT_PAYLOAD");this.appendDummyInput().appendField("QOS:").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldDropdown([["0 - at most\u00a0once",
"0"],["1 - at least\u00a0once","1"],["2 - exactly\u00a0once","2"]]),"MQTT_QOS");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(280);this.setInputsInline(!1);this.setTooltip("Publish Payload to MQTT Server");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.mqtt_subscribe={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Subscribe to MQTT topic"),"BLOCK_MQTT_SUBSCRIBE");this.appendValueInput("topic").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField(new Blockly.FieldLabelSerializable("topic"),"MQTT_TOPIC");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(280);this.setTooltip("Subscribe to MQTT Topic");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.mqtt_set_callback={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Set callback to MQTT messages"),"BLOCK_MQTT_SET_CALLBACK");this.appendDummyInput().appendField("with").appendField(new Blockly.FieldVariable("callback_msg"),"MQTT_DATA_VAR").appendField("received from").appendField(new Blockly.FieldVariable("callback_topic",null,["String"],"String"),"MQTT_TOPIC_VAR");this.appendStatementInput("do").appendField("do");this.setPreviousStatement(!0,
null);this.setNextStatement(!0,null);this.setColour(280);this.setInputsInline(!1);this.setTooltip("Callback function must have topic and msg parameters");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.mqtt_check_msg={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Check MQTT server for pending messages"),"BLOCK_MQTT_CHECK_MSG");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(280);this.setTooltip("Check if the server has any pending messages. Non-blocking method. Subscription messages will be passed to the callback.");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.mqtt_wait_msg={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Wait for MQTT server messages"),"BLOCK_MQTT_WAIT_MSG");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(280);this.setTooltip("Wait for server sending any message. Blocking method. Subscription messages will be passed to the callback.");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.mqtt_disconnect={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Disconnect MQTT client"),"BLOCK_MQTT_DISCONNECT");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(280);this.setTooltip("Disconnect the MQTT Client from Server.");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.mqtt_connect={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Connect MQTT client"),"BLOCK_MQTT_CONNECT");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(280);this.setTooltip("Connect the MQTT Client from Server.");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.relay_switch={init:function(){this.appendDummyInput().appendField(new Blockly.FieldImage("media/relay.png",55,55,"*")).setAlign(Blockly.ALIGN_CENTRE).appendField("Relay");this.appendValueInput("pin").setCheck("Number").appendField("Turn").appendField(new Blockly.FieldDropdown([["off","0"],["on","1"]]),"RELAY_STATUS").appendField("relay on pin#");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(75);this.setTooltip("Turn On Relay on GPIO digital pin");
this.setHelpUrl("bipes.net.br")}};Blockly.Blocks.text_to_str={init:function(){this.appendValueInput("var").appendField(new Blockly.FieldLabelSerializable("to str"),"VAR");this.setColour(160);this.setOutput(!0,null);this.setTooltip("Convert anything to String.");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.decode_bytes_to_text={init:function(){this.appendValueInput("var").appendField(new Blockly.FieldLabelSerializable("decode bytes to text"),"VAR");this.setColour(160);this.setOutput(!0,null);this.setTooltip("Decode bytes to a String.");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.var_to_int={init:function(){this.appendValueInput("var").appendField(new Blockly.FieldLabelSerializable("to int"),"VAR");this.setColour(230);this.setOutput(!0,null);this.setTooltip("Convert anything to Int.");this.setHelpUrl("http://www.bipes.net.br")}};Blockly.Blocks.var_to_float={init:function(){this.appendValueInput("var").appendField(new Blockly.FieldLabelSerializable("to float"),"VAR");this.setColour(230);this.setOutput(!0,null);this.setTooltip("Convert anything to float.");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.machine_unique_id={init:function(){this.appendDummyInput().appendField(" unique_id");this.setColour(0);this.setOutput(!0,null);this.setTooltip(".. function:: unique_id() Returns a byte string with a unique identifier of a board/SoC. It will vary from a board/SoC instance to another, if underlying hardware allows. Length ");this.setHelpUrl("https://docs.micropython.org/en/latest/library/machine.html")}};
Blockly.Blocks.machine_reset_cause={init:function(){this.appendDummyInput().appendField(" reset_cause");this.setColour(0);this.setOutput(!0,null);this.setTooltip(".. function:: reset_cause() Get the reset cause. See :ref:`constants <machine_constants>` for the possibl e return values. ");this.setHelpUrl("https://docs.micropython.org/en/latest/library/machine.html")}};
Blockly.Blocks.ujson_dump={init:function(){this.appendValueInput("pIn").appendField(" dump");this.setColour(340);this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setTooltip(".. function:: dump(obj, stream) Serialise *obj* to a JSON string, writing it to the given *stream*. ");this.setHelpUrl("https://docs.micropython.org/en/latest/library/ujson.html")}};
Blockly.Blocks.ujson_dumps={init:function(){this.appendValueInput("dic").setCheck("Dict").appendField(" ujson dumps");this.setColour(340);this.setOutput(!0,null);this.setTooltip(".. function:: dumps(obj) Return *obj* represented as a JSON string. ");this.setHelpUrl("https://docs.micropython.org/en/latest/library/ujson.html")}};
Blockly.Blocks.ujson_load={init:function(){this.appendValueInput("pIn").appendField(" load");this.setColour(340);this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setTooltip(".. function:: load(stream) Parse the given *stream*, interpreting it as a JSON string and deserialising the data to a Python object. The resing object is ");this.setHelpUrl("https://docs.micropython.org/en/latest/library/ujson.html")}};
Blockly.Blocks.ujson_loads={init:function(){this.appendValueInput("json_str").setCheck("String").appendField(" ujson loads");this.setOutput(!0,null);this.setColour(340);this.setTooltip(".. function:: loads(str) Parse the JSON *str* and return an object. Raises :exc:`ValueError` if the string is not correctly formed. ");this.setHelpUrl("https://docs.micropython.org/en/latest/library/ujson.html")}};
Blockly.Blocks.uos_chdir={init:function(){this.appendValueInput("path").appendField(" chdir");this.setColour(0);this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setTooltip(".. function:: chdir(path) Change current directory. ");this.setHelpUrl("https://docs.micropython.org/en/latest/library/uos.html")}};
Blockly.Blocks.uos_getcwd={init:function(){this.appendDummyInput().appendField(" getcwd");this.setColour(0);this.setOutput(!0,null);this.setTooltip(".. function:: getcwd() Get the current directory. ");this.setHelpUrl("https://docs.micropython.org/en/latest/library/uos.html")}};Blockly.Blocks.uos_ilistdir={init:function(){this.appendValueInput("path").appendField(" ilistdir");this.setColour(0);this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setTooltip(" ");this.setHelpUrl("https://docs.micropython.org/en/latest/library/uos.html")}};
Blockly.Blocks.uos_listdir={init:function(){this.appendValueInput("path").appendField(" listdir");this.setColour(0);this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setTooltip(" ");this.setHelpUrl("https://docs.micropython.org/en/latest/library/uos.html")}};
Blockly.Blocks.uos_mkdir={init:function(){this.appendDummyInput().appendField("Create new folder");this.appendValueInput("path").setAlign(Blockly.ALIGN_RIGHT).appendField("name");this.setColour(0);this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setTooltip(".. function:: mkdir(path) Create a new directory. ");this.setHelpUrl("https://docs.micropython.org/en/latest/library/uos.html")}};
Blockly.Blocks.uos_remove={init:function(){this.appendDummyInput().appendField("Delete file");this.appendValueInput("file").setAlign(Blockly.ALIGN_RIGHT).appendField("filename");this.setColour(0);this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setTooltip(".. function:: remove(path) Remove a file. ");this.setHelpUrl("https://docs.micropython.org/en/latest/library/uos.html")}};
Blockly.Blocks.uos_rmdir={init:function(){this.appendValueInput("path").appendField(" rmdir");this.setColour(0);this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setTooltip(".. function:: rmdir(path) Remove a directory. ");this.setHelpUrl("https://docs.micropython.org/en/latest/library/uos.html")}};
Blockly.Blocks.uos_rename={init:function(){this.appendValueInput("old_path").appendField(" rename old");this.appendValueInput("new_path").setAlign(Blockly.ALIGN_RIGHT).appendField("to new");this.setColour(0);this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setTooltip(".. function:: rename(old_path, new_path) Rename a file. ");this.setHelpUrl("https://docs.micropython.org/en/latest/library/uos.html")}};
Blockly.Blocks.rfid_rc522_init={init:function(){this.setColour(55);this.appendDummyInput().appendField("Init RC522 RFID Module");this.appendDummyInput().appendField(new Blockly.FieldImage("media/RC522.jpg",55,55,"*"));this.appendValueInput("sck").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("SCK#");this.appendValueInput("mosi").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("MOSI#");this.appendValueInput("miso").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("MISO#");
this.appendValueInput("rst").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("RST#");this.appendValueInput("sda").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("SDA#");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.rfid_rc522_detect_card={init:function(){this.setColour(55);this.appendDummyInput().appendField("Request if RFID card is present");this.appendValueInput("stat").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("status");this.appendValueInput("tag").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("tag");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.rfid_rc522_ok={init:function(){this.appendDummyInput().appendField(" Card/UID detected");this.setColour(55);this.setOutput(!0,null);this.setTooltip("if card detected return OK");this.setHelpUrl("https://fchart.github.io")}};
Blockly.Blocks.rfid_rc522_anticoll={init:function(){this.setColour(55);this.appendDummyInput().appendField("Get card identification (UID)");this.appendValueInput("stat").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("status");this.appendValueInput("tag").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("tag");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.rfid_rc522_get_uid_string={init:function(){this.appendValueInput("obj").setCheck("Variable").setAlign(Blockly.ALIGN_RIGHT).appendField("to RFID UID string");this.setOutput(!0,null);this.setColour(55);this.setTooltip("Get RFID UID string)");this.setHelpUrl("bipes.net.br")}};Blockly.Blocks.rfid_rc522_read_card={init:function(){this.setColour(245);this.appendDummyInput().appendField("Read RFID Card Memory");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.rfid_rc522_write_card={init:function(){this.setColour(55);this.appendDummyInput().appendField("Write RFID Card Memory");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.char_lcd_init={init:function(){this.setColour(175);this.appendDummyInput().appendField("Init I2C character LCD display");this.appendDummyInput().appendField(new Blockly.FieldImage("media/lcd20x4.jpg",55,55,"*"));this.appendValueInput("sda").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("SDA#");this.appendValueInput("scl").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("SCL#");this.appendValueInput("lines").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("lines");
this.appendValueInput("columns").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("columns");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};Blockly.Blocks.char_lcd_clear={init:function(){this.setColour(175);this.appendDummyInput().appendField("Clear LCD");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.char_lcd_putstr={init:function(){this.setColour(175);this.appendDummyInput().appendField("Write text on LCD");this.appendValueInput("text").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("text");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.char_lcd_moveto={init:function(){this.setColour(175);this.appendDummyInput().appendField("Move LCD cursor to");this.appendValueInput("x").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("x");this.appendValueInput("y").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("y");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.char_lcd_backlight={init:function(){this.setColour(175);this.appendDummyInput().appendField("LCD backlight");this.appendValueInput("state").setCheck(null).setAlign(Blockly.ALIGN_RIGHT).appendField("ON/OFF");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.char_lcd_display={init:function(){this.setColour(175);this.appendDummyInput().appendField("LCD power");this.appendValueInput("state").setCheck(null).setAlign(Blockly.ALIGN_RIGHT).appendField("ON/OFF");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.net_ntp_sync={init:function(){this.setColour(270);this.appendDummyInput().appendField("Sync date and time");this.appendDummyInput().appendField("NTP: Network Time Protocol");this.appendValueInput("tz").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("Timezone:");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.net_get_ntp={init:function(){this.appendDummyInput().appendField(new Blockly.FieldLabelSerializable("Get NTP localtime"),"GET_NTP_LOCALTIME");this.appendValueInput("year").setCheck("Variable").setAlign(Blockly.ALIGN_RIGHT).appendField("year var");this.appendValueInput("month").setCheck("Variable").setAlign(Blockly.ALIGN_RIGHT).appendField("month var");this.appendValueInput("day").setCheck("Variable").setAlign(Blockly.ALIGN_RIGHT).appendField("day var");this.appendValueInput("hour").setCheck("Variable").setAlign(Blockly.ALIGN_RIGHT).appendField("hour var");
this.appendValueInput("minute").setCheck("Variable").setAlign(Blockly.ALIGN_RIGHT).appendField("minute var");this.appendValueInput("second").setCheck("Variable").setAlign(Blockly.ALIGN_RIGHT).appendField("second var");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(270);this.setTooltip("Get NTP localtime");this.setHelpUrl("bipes.net.br")}};
Blockly.Blocks.net_socket_connect={init:function(){this.setColour(300);this.appendDummyInput().appendField("TCP/IP Socket connect");this.appendValueInput("host").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("host:");this.appendValueInput("port").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("port:");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.net_socket_receive={init:function(){this.setColour(300);this.appendDummyInput().appendField("Socket receive");this.appendValueInput("bytes").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("bytes to receive:");this.setOutput(!0);this.setTooltip("")}};
Blockly.Blocks.net_socket_send={init:function(){this.setColour(300);this.appendDummyInput().appendField("Socket send");this.appendValueInput("bytes").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("data:");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};Blockly.Blocks.net_socket_close={init:function(){this.setColour(300);this.appendDummyInput().appendField("Socket close");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.net_http_server_start={init:function(){this.setColour(320);this.appendDummyInput().appendField("Start HTTP web server");this.appendValueInput("port").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("port:");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.net_http_server_accept={init:function(){this.setColour(320);this.appendDummyInput().appendField("Wait for HTTP client");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};Blockly.Blocks.net_http_server_requested_page={init:function(){this.setColour(320);this.appendDummyInput().appendField("Requested web page");this.setOutput(!0);this.setTooltip("")}};
Blockly.Blocks.net_http_server_send_response={init:function(){this.setColour(320);this.appendDummyInput().appendField("Sent HTTP response to client");this.appendValueInput("html").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("HTML data:");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};Blockly.Blocks.net_http_server_close={init:function(){this.setColour(320);this.appendDummyInput().appendField("Close HTTP web server");this.setOutput(!0);this.setTooltip("")}};
Blockly.Blocks.stepper_init={init:function(){this.setColour(95);this.appendDummyInput().appendField("Init stepper motor");this.appendDummyInput().appendField(new Blockly.FieldImage("media/stepper.png",55,55,"*"));this.appendValueInput("p0").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("pin0#");this.appendValueInput("p1").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("pin1#");this.appendValueInput("p2").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("pin2#");
this.appendValueInput("p3").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("pin3#");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};Blockly.Blocks.stepper_step={init:function(){this.setColour(95);this.appendDummyInput().appendField("Stepper step");this.appendValueInput("steps").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("steps");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.dc_motor_init={init:function(){this.setColour(110);this.appendDummyInput().appendField("Init DC motor");this.appendDummyInput().appendField(new Blockly.FieldImage("media/dcmotor.png",55,55,"*"));this.appendValueInput("pwm").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("pwm#");this.appendValueInput("dir1").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("dir1#");this.appendValueInput("dir2").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("dir2#");
this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};Blockly.Blocks.dc_motor_power={init:function(){this.setColour(110);this.appendDummyInput().appendField("Set DC motor power");this.appendValueInput("power").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("power");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.dc_motor_direction={init:function(){this.setColour(110);this.appendDummyInput().appendField("Set DC motor direction");this.appendValueInput("dir").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("direction");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};Blockly.Blocks.dc_motor_stop={init:function(){this.setColour(110);this.appendDummyInput().appendField("Stop DC motor");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("")}};
Blockly.Blocks.python_try_catch={init:function(){this.appendDummyInput().appendField("Try/Catch");this.appendStatementInput("try").appendField("try");this.appendStatementInput("catch").appendField("catch");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(230);this.setInputsInline(!1);this.setTooltip("Python Try/Catch");this.setHelpUrl("http://www.bipes.net.br")}};
Blockly.Blocks.xtools_get_id={init:function(){this.appendDummyInput().appendField(" xtools get_id");this.setColour(40);this.setOutput(!0,null);this.setTooltip("Returns a byte string with a unique identifier of a board/SoC");this.setHelpUrl("https://fchart.github.io")}};Blockly.Blocks.xtools_get_num={init:function(){this.appendValueInput("text_str").setCheck("String").appendField(" xtools get_num");this.setOutput(!0,null);this.setColour(40);this.setTooltip("Extract number from text string");this.setHelpUrl("https://fchart.github.io")}};
Blockly.Blocks.xtools_random_in_range={init:function(){this.appendValueInput("low").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("xtools random in range low");this.appendValueInput("high").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("high");this.setOutput(!0,null);this.setColour(40);this.setTooltip("Generating Random Numbers in a Range");this.setHelpUrl("https://fchart.github.io")}};
Blockly.Blocks.xtools_map_range={init:function(){this.appendValueInput("in_min").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("xtools map range in min");this.appendValueInput("in_max").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("in max");this.appendValueInput("out_min").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("out min");this.appendValueInput("out_max").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("out max");this.setOutput(!0,null);
this.setColour(40);this.setTooltip("Re-maps a number from one range to another");this.setHelpUrl("https://fchart.github.io")}};
Blockly.Blocks.xtools_connect_wifi={init:function(){this.appendDummyInput().appendField("xtools connect to Wifi netowrk");this.appendValueInput("ssid").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("Network name");this.appendValueInput("pwd").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("Network key");this.appendValueInput("timeout").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("timeout");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);
this.setColour(40);this.setTooltip("Connect to wifi network with LED indicator");this.setHelpUrl("https://fchart.github.io")}};
Blockly.Blocks.xtools_connect_wifi_ip={init:function(){this.appendDummyInput().appendField("xtools connect to Wifi netowrk");this.appendValueInput("ssid").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("Network name");this.appendValueInput("pwd").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("Network key");this.appendValueInput("timeout").setCheck("Number").setAlign(Blockly.ALIGN_RIGHT).appendField("timeout");this.setOutput(!0,null);this.setColour(40);this.setTooltip("Connect to wifi network with LED indicator and return IP address");
this.setHelpUrl("https://fchart.github.io")}};Blockly.Blocks.xtools_webhook_post={init:function(){this.appendValueInput("URL").setCheck("String").appendField("Make xtools webhook POST Request URL");this.appendValueInput("json").setAlign(Blockly.ALIGN_RIGHT).appendField("json");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(40);this.setTooltip("Make Webhook HTTP POST Request");this.setHelpUrl("https://fchart.github.io")}};
Blockly.Blocks.xtools_webhook_get={init:function(){this.appendValueInput("URL").setCheck("String").appendField("Make xtools webhook GET Request URL");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(40);this.setTooltip("Make Webhook HTTP GET Request");this.setHelpUrl("https://fchart.github.io")}};
Blockly.Blocks.xtools_line_msg={init:function(){this.appendValueInput("token").setCheck("String").appendField("Send xrequests LINE notify token");this.appendValueInput("message").setCheck("String").setAlign(Blockly.ALIGN_RIGHT).appendField("message");this.setPreviousStatement(!0,null);this.setNextStatement(!0,null);this.setColour(40);this.setTooltip("Send LINE Notify Message");this.setHelpUrl("https://fchart.github.io")}};