var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};
Blockly.Python.neopixel_initialise=function(a){Blockly.Python.definitions_.import_neopixel="import neopixel";Blockly.Python.definitions_.import_pin="from machine import Pin";var b=a.getFieldValue("n");a=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE);return"np"+a+"_number = "+b+"\nnp"+a+" = neopixel.NeoPixel(Pin("+a+"), "+b+")\n"};
Blockly.Python.neopixel_clear=function(a){a=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE);Blockly.Python.definitions_.import_neopixel="import neopixel";Blockly.Python.definitions_.neopixel_clear="def np_clear(np, n):\n  for i in range(n):\n    np[i] = (0, 0, 0)\n    np.write()\n";return"np_clear(np"+a+", np"+a+"_number)\n"};
Blockly.Python.neopixel_show=function(a){Blockly.Python.definitions_.import_neopixel="import neopixel";return"np"+Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE)+".write()\n"};
Blockly.Python.neopixel_set=function(a){var b=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE),c=Blockly.Python.valueToCode(a,"pixel",Blockly.Python.ORDER_ATOMIC),d=Blockly.Python.valueToCode(a,"red",Blockly.Python.ORDER_ATOMIC),e=Blockly.Python.valueToCode(a,"green",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"blue",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_neopixel="import neopixel";return"np"+b+"["+c+"] = ("+d+", "+e+", "+a+")\n"};
Blockly.Python.neopixel_get=function(a){var b=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE),c=Blockly.Python.valueToCode(a,"pixel",Blockly.Python.ORDER_ATOMIC),d=Blockly.Python.valueToCode(a,"red",Blockly.Python.ORDER_ATOMIC),e=Blockly.Python.valueToCode(a,"green",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"blue",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_neopixel="import neopixel";return d+", "+e+", "+a+" = np"+b+"["+c+"]\n"};
Blockly.Python.neopixel_bounce=function(a){var b=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE),c=Blockly.Python.valueToCode(a,"red",Blockly.Python.ORDER_ATOMIC),d=Blockly.Python.valueToCode(a,"green",Blockly.Python.ORDER_ATOMIC),e=Blockly.Python.valueToCode(a,"blue",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"delay",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_neopixel="import neopixel";Blockly.Python.definitions_.import_utime="import utime";Blockly.Python.definitions_.neopixel_bounce=
"def np_bounce(np, n, r, g, b, ms):\n  for i in range(4 * n):\n    for j in range(n):\n      np[j] = (r, g, b)\n    if (i // n) % 2 == 0:\n      np[i % n] = (0, 0, 0)\n    else:\n      np[n-1-(i % n)] = (0, 0, 0)\n    np.write()\n    utime.sleep_ms(ms)\n";return"np_bounce(np"+b+", np"+b+"_number, "+c+", "+d+", "+e+", "+a+")\n"};
Blockly.Python.neopixel_cycle=function(a){var b=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE),c=Blockly.Python.valueToCode(a,"red",Blockly.Python.ORDER_ATOMIC),d=Blockly.Python.valueToCode(a,"green",Blockly.Python.ORDER_ATOMIC),e=Blockly.Python.valueToCode(a,"blue",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"delay",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_neopixel="import neopixel";Blockly.Python.definitions_.import_utime="import utime";Blockly.Python.definitions_.neopixel_cycle=
"def np_cycle(np, n, r, g, b, ms):\n  for i in range(4 * n):\n    for j in range(n):\n      np[j] = (0, 0, 0)\n    np[i % n] = (r, g, b)\n    np.write()\n    utime.sleep_ms(ms)\n";return"np_cycle(np"+b+", np"+b+"_number, "+c+", "+d+", "+e+", "+a+")\n"};Blockly.Python.dict_get=function(a){var b=Blockly.Python.valueToCode(a,"DICT",Blockly.Python.ORDER_MEMBER)||"{}";a=Blockly.Python.valueToCode(a,"ITEM",Blockly.Python.ORDER_NONE)||"None";return[b+"["+a+"]",Blockly.Python.ORDER_ATOMIC]};
Blockly.Python.dict_set=function(a){var b=Blockly.Python.valueToCode(a,"DICT",Blockly.Python.ORDER_MEMBER)||"{}",c=Blockly.Python.valueToCode(a,"ITEM",Blockly.Python.ORDER_NONE)||"None";a=Blockly.Python.valueToCode(a,"VALUE",Blockly.Python.ORDER_NONE)||"None";return b+"["+c+"] = "+a+"\n"};
Blockly.Python.dicts_create_with=function(a){Blockly.Python.valueToCode(a,"keys",Blockly.Python.ORDER_ATOMIC);for(var b=Array(a.itemCount_),c=0;c<a.itemCount_;c++){var d=Blockly.Python.valueToCode(a,"KEY"+c,Blockly.Python.ORDER_NONE)||"None",e=Blockly.Python.valueToCode(a,"VALUE"+c,Blockly.Python.ORDER_NONE)||"None";b[c]=d+": "+e}b="{"+b.join(",\n\t")+"}";return[b,Blockly.Python.ORDER_ATOMIC]};
Blockly.Python.delay=function(a){a=Blockly.Python.valueToCode(a,"time",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_time="import utime";return"utime.sleep("+a+")\n"};Blockly.Python.reset=function(a){Blockly.Python.definitions_.import_machine="import machine";return"machine.reset()\n"};Blockly.Python.soft_reset=function(a){Blockly.Python.definitions_.import_machine="import machine";return"machine.soft_reset()\n"};
Blockly.Python.reset_cause_soft=function(a){Blockly.Python.definitions_.import_machine="import machine";return["machine.SOFT_RESET",Blockly.JavaScript.ORDER_MEMBER]};Blockly.Python.reset_cause_hard=function(a){Blockly.Python.definitions_.import_machine="import machine";return["machine.HARD_RESET",Blockly.JavaScript.ORDER_MEMBER]};Blockly.Python.reset_cause_wdt=function(a){Blockly.Python.definitions_.import_machine="import machine";return["machine.WDT_RESET",Blockly.JavaScript.ORDER_MEMBER]};
Blockly.Python.reset_cause_deep=function(a){Blockly.Python.definitions_.import_machine="import machine";return["machine.DEEPSLEEP_RESET",Blockly.JavaScript.ORDER_MEMBER]};Blockly.Python.exec_python=function(a){return Blockly.Python.valueToCode(a,"command",Blockly.Python.ORDER_ATOMIC).replace(/^"/,"").replace(/"$/,"").replace(/^'/,"").replace(/'$/,"")+"\n"};
Blockly.Python.exec_import_python_module=function(a){a=Blockly.Python.valueToCode(a,"command",Blockly.Python.ORDER_ATOMIC).replace(/^"/,"").replace(/"$/,"");Blockly.Python.definitions_[a]=a.replace(/^'/,"").replace(/'$/,"");return""};Blockly.Python.set_freq=function(a){Blockly.Python.definitions_.import_machine="import machine";return"machine.freq("+Blockly.Python.valueToCode(a,"freq",Blockly.Python.ORDER_ATOMIC)+")\n"};
Blockly.Python.get_freq=function(a){Blockly.Python.definitions_.import_machine="import machine";return["machine.freq()",Blockly.Python.ORDER_NONE]};Blockly.Python.exec_python_output=function(a){return[Blockly.Python.valueToCode(a,"command",Blockly.Python.ORDER_ATOMIC).replace(/^"/,"").replace(/"$/,""),Blockly.Python.ORDER_MEMBER]};
Blockly.Python.exec_python_func=function(a){return[Blockly.Python.valueToCode(a,"command",Blockly.Python.ORDER_ATOMIC).replace(/^"/,"").replace(/"$/,"").replace(/^'/,"").replace(/'$/,""),Blockly.Python.ORDER_MEMBER]};Blockly.Python.run_cmd=function(a){a=Blockly.Python.valueToCode(a,"command",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_os="import os";return"os.system("+a+")\n"};
Blockly.Python.play_mp3=function(a){a=Blockly.Python.valueToCode(a,"command",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_os="import os";return"os.system('mpg123 "+a.replace(/^'/,"").replace(/'$/,"")+"') \n"};
Blockly.Python.gpio_set=function(a){var b=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE);a=Blockly.Python.valueToCode(a,"value",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_pin="from machine import Pin";Blockly.Python.definitions_["gpio_set"+b]="pOut"+b+" = Pin("+b+", Pin.OUT)\n\n";a="True"==a||1==a?1:"False"==a||0==a?0:a.replace(/^\(/,"").replace(/\)$/,"");return"pOut"+b+".value("+a+")\n"};
Blockly.Python.gpio_set_mehtod_chaining=function(a){var b=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE);a=Blockly.Python.valueToCode(a,"value",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_pin="from machine import Pin";a="True"==a||1==a?1:"False"==a||0==a?0:a.replace(/^\(/,"").replace(/\)$/,"");return"Pin("+b+", Pin.OUT).value("+a+")\n"};
Blockly.Python.adc=function(a){Blockly.Python.definitions_.import_adc="from machine import ADC";a=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.init_adc="adc"+a+" = ADC("+a+")";return["adc"+a+".read()",Blockly.Python.ORDER_NONE]};
Blockly.Python.gpio_get=function(a){a=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE);Blockly.Python.definitions_.import_pin="from machine import Pin";Blockly.Python.definitions_["gpio_get"+a]="pIn"+a+" = Pin("+a+", Pin.IN, Pin.PULL_UP)\n\n";return["pIn"+a+".value()",Blockly.Python.ORDER_MEMBER]};
Blockly.Python.gpio_get_out=function(a){a=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE);Blockly.Python.definitions_.import_pin="from machine import Pin";Blockly.Python.definitions_["gpio_set"+a]="pOut"+a+" = Pin("+a+", Pin.OUT)\n\n";return["pOut"+a+".value()",Blockly.Python.ORDER_MEMBER]};
Blockly.Python.pwm=function(a){var b=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE),c=Blockly.Python.valueToCode(a,"frequency",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"duty",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_pin="from machine import Pin";Blockly.Python.definitions_.import_pwm="from machine import PWM";Blockly.Python.definitions_["pwm"+b]="pPWM"+b+" = PWM(Pin("+b+"), freq="+c+", duty="+a+")\n\n";return""};
Blockly.Python.pwm_duty=function(a){var b=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE);a=Blockly.Python.valueToCode(a,"duty",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_pin="from machine import Pin";Blockly.Python.definitions_.import_pwm="from machine import PWM";return"pPWM"+b+".duty("+a+")\n"};
Blockly.Python.gpio_create_pinobj=function(a){var b=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE);a=a.getFieldValue("type");Blockly.Python.definitions_.import_pin="from machine import Pin";b="Pin("+b+", Pin."+a;"IN"==a&&(b+=", Pin.PULL_UP");return[b+")",Blockly.Python.ORDER_NONE]};
Blockly.Python.gpio_set_pinobj=function(a){var b=Blockly.Python.valueToCode(a,"obj",Blockly.Python.ORDER_NONE);a=Blockly.Python.valueToCode(a,"value",Blockly.Python.ORDER_ATOMIC);a="True"==a||1==a?1:"False"==a||0==a?0:a.replace(/^\(/,"").replace(/\)$/,"");return b+".value("+a+")\n"};Blockly.Python.gpio_get_pinobj=function(a){a=Blockly.Python.valueToCode(a,"obj",Blockly.Python.ORDER_NONE);Blockly.Python.definitions_.import_pin="from machine import Pin";return[a+".value()",Blockly.Python.ORDER_MEMBER]};
Blockly.Python.gpio_create_pwmobj=function(a){var b=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE),c=Blockly.Python.valueToCode(a,"frequency",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"duty",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_pin="from machine import Pin";Blockly.Python.definitions_.import_pwm="from machine import PWM";return["PWM(Pin("+b+"), freq="+c+", duty="+a+")",Blockly.Python.ORDER_NONE]};
Blockly.Python.gpio_pwmobj_duty=function(a){var b=Blockly.Python.valueToCode(a,"obj",Blockly.Python.ORDER_NONE);a=Blockly.Python.valueToCode(a,"duty",Blockly.Python.ORDER_ATOMIC);return b+".duty("+a+")\n"};Blockly.Python.gpio_pwmobj_freq=function(a){var b=Blockly.Python.valueToCode(a,"obj",Blockly.Python.ORDER_NONE);a=Blockly.Python.valueToCode(a,"freq",Blockly.Python.ORDER_ATOMIC);return b+".freq("+a+")\n"};
Blockly.Python.gpio_pwmobj_deinit=function(a){return Blockly.Python.valueToCode(a,"obj",Blockly.Python.ORDER_NONE)+".deinit()\n"};Blockly.Python.pinout=function(a){return[a.getFieldValue("PIN"),Blockly.Python.ORDER_NONE]};Blockly.Python.text_to_str=function(a){return["str("+Blockly.Python.valueToCode(a,"var",Blockly.Python.ORDER_NONE)+")",Blockly.Python.ORDER_MEMBER]};Blockly.Python.decode_bytes_to_text=function(a){return[Blockly.Python.valueToCode(a,"var",Blockly.Python.ORDER_NONE)+".decode()",Blockly.Python.ORDER_MEMBER]};
Blockly.Python.var_to_int=function(a){return["int("+Blockly.Python.valueToCode(a,"var",Blockly.Python.ORDER_NONE)+")",Blockly.Python.ORDER_MEMBER]};Blockly.Python.var_to_float=function(a){return["float("+Blockly.Python.valueToCode(a,"var",Blockly.Python.ORDER_NONE)+")",Blockly.Python.ORDER_MEMBER]};
Blockly.Python.onewire_ds18x20_init=function(a){a=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE);Blockly.Python.definitions_.import_pin="from machine import Pin";Blockly.Python.definitions_.import_onewire="import onewire";Blockly.Python.definitions_.import_ds18x20="import ds18x20";return"onewire = onewire.OneWire(Pin("+a+"))\nds = ds18x20.DS18X20(onewire)\n"};Blockly.Python.onewire_ds18x20_scan=function(a){return["ds.scan()",Blockly.Python.ORDER_NONE]};
Blockly.Python.onewire_ds18x20_convert=function(a){return"ds.convert_temp()\n"};Blockly.Python.onewire_ds18x20_read_temp=function(a){return["ds.read_temp("+Blockly.Python.valueToCode(a,"item",Blockly.Python.ORDER_NONE)+")",Blockly.Python.ORDER_NONE]};
Blockly.Python.init_mpu6050=function(a){var b=Blockly.Python.valueToCode(a,"scl",Blockly.Python.ORDER_NONE);a=Blockly.Python.valueToCode(a,"sda",Blockly.Python.ORDER_NONE);Blockly.Python.definitions_.import_imu="import imu";return"imu.init_MPU("+b+", "+a+")\nimu.calibrate_sensors()\n"};Blockly.Python.mpu6050_read_acc_x=function(a){return["imu.read_mpu6050v(1)",Blockly.Python.ORDER_NONE]};Blockly.Python.mpu6050_read_acc_y=function(a){return["imu.read_mpu6050v(2)",Blockly.Python.ORDER_NONE]};
Blockly.Python.mpu6050_read_acc_z=function(a){return["imu.read_mpu6050v(3)",Blockly.Python.ORDER_NONE]};Blockly.Python.mpu6050_read_gyro_x=function(a){return["imu.read_mpu6050v(4)",Blockly.Python.ORDER_NONE]};Blockly.Python.mpu6050_read_gyro_y=function(a){return["imu.read_mpu6050v(5)",Blockly.Python.ORDER_NONE]};Blockly.Python.mpu6050_read_gyro_z=function(a){return["imu.read_mpu6050v(6)",Blockly.Python.ORDER_NONE]};
Blockly.Python.init_oled=function(a){var b=Blockly.Python.valueToCode(a,"scl",Blockly.Python.ORDER_NONE),c=Blockly.Python.valueToCode(a,"sda",Blockly.Python.ORDER_NONE),d=Blockly.Python.valueToCode(a,"width",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"height",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_pin="from machine import Pin";Blockly.Python.definitions_.import_oled_a="from machine import I2C";Blockly.Python.definitions_.import_ssd="import ssd1306";b="i2c = I2C(-1, scl=Pin("+
b+"), sda=Pin("+c+"))\noled_width = "+(d+"\noled_height = ")+(a+"\n");return b+="oled = ssd1306.SSD1306_I2C(oled_width, oled_height, i2c, 0x3c)\n"};Blockly.Python.power_oled=function(a){return"True"==Blockly.Python.valueToCode(a,"state",Blockly.Python.ORDER_ATOMIC)?"oled.poweron()\n":"oled.poweroff()\n"};Blockly.Python.clear_oled=function(a){return"oled.fill(0)\n"};Blockly.Python.show_oled=function(a){return"oled.show()\n"};
Blockly.Python.fill_oled=function(a){return"oled.fill("+Blockly.Python.valueToCode(a,"value",Blockly.Python.ORDER_ATOMIC)+")\n"};Blockly.Python.write_oled=function(a){var b=Blockly.Python.valueToCode(a,"x",Blockly.Python.ORDER_ATOMIC),c=Blockly.Python.valueToCode(a,"y",Blockly.Python.ORDER_ATOMIC);return"oled.text("+Blockly.Python.valueToCode(a,"text",Blockly.Python.ORDER_ATOMIC)+", int("+b+"), int("+c+"))\n"};
Blockly.Python.max7219_init=function(a){Blockly.Python.valueToCode(a,"din",Blockly.Python.ORDER_NONE);var b=Blockly.Python.valueToCode(a,"cs",Blockly.Python.ORDER_NONE);Blockly.Python.valueToCode(a,"clk",Blockly.Python.ORDER_NONE);a=Blockly.Python.valueToCode(a,"num",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_max7219="import max7219";Blockly.Python.definitions_.import_pin="from machine import Pin";Blockly.Python.definitions_.import_spi="from machine import SPI";return"MAX7219_NUM = "+
a+"\nspi = SPI(1, baudrate=10000000, polarity=0, phase=0)\ndisp = max7219.Matrix8x8(spi, Pin("+b+"), MAX7219_NUM)\n"};Blockly.Python.max7219_brightness=function(a){return"disp.brightness("+Blockly.Python.valueToCode(a,"value",Blockly.Python.ORDER_ATOMIC)+")\n"};Blockly.Python.max7219_clear=function(a){return"disp.fill(0)\n"};
Blockly.Python.max7219_write=function(a){var b=Blockly.Python.valueToCode(a,"x",Blockly.Python.ORDER_ATOMIC),c=Blockly.Python.valueToCode(a,"y",Blockly.Python.ORDER_ATOMIC);return"disp.text("+Blockly.Python.valueToCode(a,"text",Blockly.Python.ORDER_ATOMIC)+", int("+b+"), int("+c+"), 1)\n"};
Blockly.Python.max7219_scroll=function(a){var b=Blockly.Python.valueToCode(a,"delayms",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"text",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_utime="import utime";Blockly.Python.definitions_.max7219_scrolltext="def max7219_scrolltext(num, txt, delayms):\n  for idx in range(num * 8, len(txt) * -8 -1, -1):\n    disp.fill(0)\n    disp.text(txt, idx, 0, 1)\n    disp.show()\n    utime.sleep_ms(delayms)\n";return"max7219_scrolltext(MAX7219_NUM, "+
a+", "+b+")\n"};Blockly.Python.max7219_show=function(a){return"disp.show()\n"};Blockly.Python.init_servo=function(a){a=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE);Blockly.Python.definitions_.import_machine="import machine";return"pservo"+a+" = machine.Pin("+a+")\nservo"+(a+" = machine.PWM(pservo"+a+",freq=50)\n")};
Blockly.Python.move_servo=function(a){var b=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE);a=Blockly.Python.valueToCode(a,"angle",Blockly.Python.ORDER_ATOMIC);return"servo"+b+".duty("+a+")\n"};Blockly.Python.net_get_request=function(a){a=Blockly.Python.valueToCode(a,"URL",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_urequests="import urequests";return["urequests.get("+a+")",Blockly.Python.ORDER_NONE]};
Blockly.Python.net_get_request_headers=function(a){var b=Blockly.Python.valueToCode(a,"URL",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"headers",Blockly.Python.ORDER_ATOMIC)||"";Blockly.Python.definitions_.import_urequests="import urequests";b="urequests.get("+b;0!=a.length&&(b=b+", headers="+a);return[b+")\n",Blockly.Python.ORDER_NONE]};Blockly.Python.net_response_statuscode=function(a){return[Blockly.Python.valueToCode(a,"response",Blockly.Python.ORDER_ATOMIC)+".status_code",Blockly.Python.ORDER_MEMBER]};
Blockly.Python.net_response_text=function(a){return[Blockly.Python.valueToCode(a,"response",Blockly.Python.ORDER_ATOMIC)+".text",Blockly.Python.ORDER_MEMBER]};Blockly.Python.net_response_encoding=function(a){return[Blockly.Python.valueToCode(a,"response",Blockly.Python.ORDER_ATOMIC)+".encoding",Blockly.Python.ORDER_MEMBER]};Blockly.Python.net_response_json=function(a){return[Blockly.Python.valueToCode(a,"response",Blockly.Python.ORDER_ATOMIC)+".json()",Blockly.Python.ORDER_MEMBER]};
Blockly.Python.net_response_json_get=function(a){var b=Blockly.Python.valueToCode(a,"json",Blockly.Python.ORDER_MEMBER)||"{}";a=(Blockly.Python.valueToCode(a,"item",Blockly.Python.ORDER_NONE)||"None").replace(/^'/,"").replace(/'$/,"").split(",");for(idx=0;idx<a.length;idx++){var c=a[idx].trim();/^\+?(0|[1-9]\d*)$/.test(c)?(c=parseInt(c)-1,b=b+"["+c+"]"):b=b+"['"+c+"']"}return[b,Blockly.Python.ORDER_ATOMIC]};
Blockly.Python.net_post_request=function(a){var b=Blockly.Python.valueToCode(a,"URL",Blockly.Python.ORDER_ATOMIC),c=Blockly.Python.valueToCode(a,"data",Blockly.Python.ORDER_ATOMIC)||"";a=Blockly.Python.valueToCode(a,"json",Blockly.Python.ORDER_ATOMIC)||"";Blockly.Python.definitions_.import_urequests="import urequests";b="urequests.post("+b;0!=c.length&&(b=b+", data="+c);0!=a.length&&(b=b+", json="+a);return[b+")\n",Blockly.Python.ORDER_NONE]};
Blockly.Python.net_get_request_params=function(a){var b=Blockly.Python.valueToCode(a,"URL",Blockly.Python.ORDER_ATOMIC),c=Blockly.Python.valueToCode(a,"params",Blockly.Python.ORDER_ATOMIC)||"";a=Blockly.Python.valueToCode(a,"headers",Blockly.Python.ORDER_ATOMIC)||"";Blockly.Python.definitions_.import_xurequests="import xurequests";b="xrequests.get("+b;0!=c.length&&(b=b+", params="+c);0!=a.length&&(b=b+", headers="+a);return[b+")\n",Blockly.Python.ORDER_NONE]};
Blockly.Python.net_post_request_headers=function(a){var b=Blockly.Python.valueToCode(a,"URL",Blockly.Python.ORDER_ATOMIC),c=Blockly.Python.valueToCode(a,"data",Blockly.Python.ORDER_ATOMIC)||"";a=Blockly.Python.valueToCode(a,"headers",Blockly.Python.ORDER_ATOMIC)||"";Blockly.Python.definitions_.import_xurequests="import xrequests";b="xrequests.post("+b;0!=c.length&&(b=b+", data="+c);0!=a.length&&(b=b+", headers="+a);return[b+")\n",Blockly.Python.ORDER_NONE]};
Blockly.Python.net_post_request_json=function(a){var b=Blockly.Python.valueToCode(a,"URL",Blockly.Python.ORDER_ATOMIC),c=Blockly.Python.valueToCode(a,"data",Blockly.Python.ORDER_ATOMIC)||"",d=Blockly.Python.valueToCode(a,"json",Blockly.Python.ORDER_ATOMIC)||"";a=Blockly.Python.valueToCode(a,"headers",Blockly.Python.ORDER_ATOMIC)||"";Blockly.Python.definitions_.import_xurequests="import xrequests";b="xrequests.post("+b;0!=c.length&&(b=b+", data="+c);0!=d.length&&(b=b+", json="+d);0!=a.length&&(b=b+
", headers="+a);return[b+")\n",Blockly.Python.ORDER_NONE]};Blockly.Python.net_ifconfig=function(a){Blockly.Python.definitions_.import_network="import network";Blockly.Python.definitions_.import_network_a="sta_if = network.WLAN(network.STA_IF)";Blockly.Python.definitions_.import_network_b="sta_if.active(True)";return["sta_if.ifconfig()",Blockly.Python.ORDER_NONE]};
Blockly.Python.net_isconnected=function(a){Blockly.Python.definitions_.import_network="import network";Blockly.Python.definitions_.import_network_a="sta_if = network.WLAN(network.STA_IF)";Blockly.Python.definitions_.import_network_b="sta_if.active(True)";return["sta_if.isconnected()",Blockly.Python.ORDER_NONE]};
Blockly.Python.net_disconnect=function(a){Blockly.Python.definitions_.import_network="import network";Blockly.Python.definitions_.import_network_a="sta_if = network.WLAN(network.STA_IF)";Blockly.Python.definitions_.import_network_b="sta_if.active(True)";return"sta_if.disconnect()\n"};
Blockly.Python.net_ap_mode=function(a){var b=Blockly.Python.valueToCode(a,"wifi_essid",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"wifi_key",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_network="import network";return"ap = network.WLAN(network.AP_IF) \nap.active(True) \nap.config(essid="+b+", password="+a+") \n"};
Blockly.Python.wifi_client_connect=function(a){var b=Blockly.Python.valueToCode(a,"wifi_client_essid",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"wifi_client_key",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_network="import network";Blockly.Python.definitions_.import_network_a="sta_if = network.WLAN(network.STA_IF)";Blockly.Python.definitions_.import_network_b="sta_if.active(True)";return'if not sta_if.isconnected():\n   print("Waiting for Wifi connection")\n   sta_if.connect('+
b+","+a+') \n   while not sta_if.isconnected():\n      pass\nprint("Connected")\n'};Blockly.Python.wifi_client_scan_networks=function(a){Blockly.Python.definitions_.import_network="import network";Blockly.Python.definitions_.import_network_a="sta_if = network.WLAN(network.STA_IF)";Blockly.Python.definitions_.import_network_b="sta_if.active(True)";return["sta_if.scan()",Blockly.Python.ORDER_NONE]};
Blockly.Python.dht_init=function(a){var b=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE);a=a.getFieldValue("DHT_TYPE");Blockly.Python.definitions_.import_pin="from machine import Pin";Blockly.Python.definitions_.import_dht="import dht";return"dhts = dht."+a+"(Pin("+b+"))\n"};Blockly.Python.dht_measure=function(a){return"dhts.measure()\n"};Blockly.Python.dht_read_temp=function(a){return["dhts.temperature()",Blockly.Python.ORDER_NONE]};
Blockly.Python.dht_read_humidity=function(a){return["dhts.humidity()",Blockly.Python.ORDER_NONE]};Blockly.Python.tm1640_init=function(a){Blockly.Python.valueToCode(a,"clk",Blockly.Python.ORDER_NONE);Blockly.Python.valueToCode(a,"dio",Blockly.Python.ORDER_NONE);Blockly.Python.definitions_.import_tm1640="import tm1640";Blockly.Python.definitions_.import_pin="from machine import Pin";return"tm = tm1640.TM1640(clk=Pin(14), dio=Pin(13))\n"};
Blockly.Python.tm1640_write=function(a){return"tm.write(["+Blockly.Python.valueToCode(a,"vector",Blockly.Python.ORDER_NONE)+"])\n"};Blockly.Python.tm1640_brig=function(a){return"tm.brightness("+Blockly.Python.valueToCode(a,"brig",Blockly.Python.ORDER_ATOMIC)+")\n"};
Blockly.Python.tm1640_num=function(a){return"digits = [0x3c66666e76663c00, 0x7e1818181c181800, 0x7e060c3060663c00, 0x3c66603860663c00, 0x30307e3234383000, 0x3c6660603e067e00, 0x3c66663e06663c00, 0x1818183030667e00, 0x3c66663c66663c00, 0x3c66607c66663c00]\ntm.write_int(digits["+Blockly.Python.valueToCode(a,"num",Blockly.Python.ORDER_ATOMIC)+"])\n"};
Blockly.Python.tm1640_custom=function(a){var b="TRUE"==a.getFieldValue("A0"),c="TRUE"==a.getFieldValue("A1"),d="TRUE"==a.getFieldValue("A2"),e="TRUE"==a.getFieldValue("A3"),f="TRUE"==a.getFieldValue("A4"),h="TRUE"==a.getFieldValue("A5"),g="TRUE"==a.getFieldValue("A6"),l="TRUE"==a.getFieldValue("A7"),m="TRUE"==a.getFieldValue("B0"),n="TRUE"==a.getFieldValue("B1"),p="TRUE"==a.getFieldValue("B2"),q="TRUE"==a.getFieldValue("B3"),r="TRUE"==a.getFieldValue("B4"),t="TRUE"==a.getFieldValue("B5"),u="TRUE"==
a.getFieldValue("B6"),v="TRUE"==a.getFieldValue("B7"),w="TRUE"==a.getFieldValue("C0"),x="TRUE"==a.getFieldValue("C1"),y="TRUE"==a.getFieldValue("C2"),z="TRUE"==a.getFieldValue("C3"),A="TRUE"==a.getFieldValue("C4"),B="TRUE"==a.getFieldValue("C5"),C="TRUE"==a.getFieldValue("C6"),D="TRUE"==a.getFieldValue("C7");a.getFieldValue("D0");a.getFieldValue("D1");a.getFieldValue("D2");a.getFieldValue("D3");a.getFieldValue("D4");a.getFieldValue("D5");a.getFieldValue("D6");a.getFieldValue("D7");var k="TRUE"==a.getFieldValue("E0"),
E="TRUE"==a.getFieldValue("E1"),F="TRUE"==a.getFieldValue("E2"),G="TRUE"==a.getFieldValue("E3"),H="TRUE"==a.getFieldValue("E4"),I="TRUE"==a.getFieldValue("E5"),J="TRUE"==a.getFieldValue("E6"),K="TRUE"==a.getFieldValue("E7"),L="TRUE"==a.getFieldValue("F0"),M="TRUE"==a.getFieldValue("F1"),N="TRUE"==a.getFieldValue("F2"),O="TRUE"==a.getFieldValue("F3"),P="TRUE"==a.getFieldValue("F4"),Q="TRUE"==a.getFieldValue("F5"),R="TRUE"==a.getFieldValue("F6"),S="TRUE"==a.getFieldValue("F7"),T="TRUE"==a.getFieldValue("G0"),
U="TRUE"==a.getFieldValue("G1"),V="TRUE"==a.getFieldValue("G2"),W="TRUE"==a.getFieldValue("G3"),X="TRUE"==a.getFieldValue("G4"),Y="TRUE"==a.getFieldValue("G5"),Z="TRUE"==a.getFieldValue("G6"),aa="TRUE"==a.getFieldValue("G7"),ba="TRUE"==a.getFieldValue("H0"),ca="TRUE"==a.getFieldValue("H1"),da="TRUE"==a.getFieldValue("H2"),ea="TRUE"==a.getFieldValue("H3"),fa="TRUE"==a.getFieldValue("H4"),ha="TRUE"==a.getFieldValue("H5"),ia="TRUE"==a.getFieldValue("H6");a="TRUE"==a.getFieldValue("H7");k=Number(k)*Math.pow(2,
0)+Number(E)*Math.pow(2,1)+Number(F)*Math.pow(2,2)+Number(G)*Math.pow(2,3)+Number(H)*Math.pow(2,4)+Number(I)*Math.pow(2,5)+Number(J)*Math.pow(2,6)+Number(K)*Math.pow(2,7);return"tm.write(["+(Number(ba)*Math.pow(2,0)+Number(ca)*Math.pow(2,1)+Number(da)*Math.pow(2,2)+Number(ea)*Math.pow(2,3)+Number(fa)*Math.pow(2,4)+Number(ha)*Math.pow(2,5)+Number(ia)*Math.pow(2,6)+Number(a)*Math.pow(2,7))+","+(Number(T)*Math.pow(2,0)+Number(U)*Math.pow(2,1)+Number(V)*Math.pow(2,2)+Number(W)*Math.pow(2,3)+Number(X)*
Math.pow(2,4)+Number(Y)*Math.pow(2,5)+Number(Z)*Math.pow(2,6)+Number(aa)*Math.pow(2,7))+","+(Number(L)*Math.pow(2,0)+Number(M)*Math.pow(2,1)+Number(N)*Math.pow(2,2)+Number(O)*Math.pow(2,3)+Number(P)*Math.pow(2,4)+Number(Q)*Math.pow(2,5)+Number(R)*Math.pow(2,6)+Number(S)*Math.pow(2,7))+","+k+","+k+","+(Number(w)*Math.pow(2,0)+Number(x)*Math.pow(2,1)+Number(y)*Math.pow(2,2)+Number(z)*Math.pow(2,3)+Number(A)*Math.pow(2,4)+Number(B)*Math.pow(2,5)+Number(C)*Math.pow(2,6)+Number(D)*Math.pow(2,7))+","+(Number(m)*
Math.pow(2,0)+Number(n)*Math.pow(2,1)+Number(p)*Math.pow(2,2)+Number(q)*Math.pow(2,3)+Number(r)*Math.pow(2,4)+Number(t)*Math.pow(2,5)+Number(u)*Math.pow(2,6)+Number(v)*Math.pow(2,7))+","+(Number(b)*Math.pow(2,0)+Number(c)*Math.pow(2,1)+Number(d)*Math.pow(2,2)+Number(e)*Math.pow(2,3)+Number(f)*Math.pow(2,4)+Number(h)*Math.pow(2,5)+Number(g)*Math.pow(2,6)+Number(l)*Math.pow(2,7))+"])\n"};
Blockly.Python.relay_switch=function(a){var b=Blockly.Python.valueToCode(a,"pin",Blockly.Python.ORDER_NONE);a=a.getFieldValue("RELAY_STATUS");Blockly.Python.definitions_.import_machine="import machine";return"1"==a?"machine.Pin("+b+", machine.Pin.OUT).off()\n":"machine.Pin("+b+", machine.Pin.OUT).on()\n"};
Blockly.Python.mqtt_add_to_buffer=function(a){var b=Blockly.Python.valueToCode(a,"fieldname",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"value",Blockly.Python.ORDER_ATOMIC);return"mqtt_buffer += ("+b+' + "=" + str('+a+')) if not len(mqtt_buffer) else ("&" + '+b+' + "=" + str('+a+"))\n"};
Blockly.Python.mqtt_init=function(a){var b=Blockly.Python.valueToCode(a,"clientid",Blockly.Python.ORDER_ATOMIC),c=Blockly.Python.valueToCode(a,"server",Blockly.Python.ORDER_ATOMIC),d=Blockly.Python.valueToCode(a,"port",Blockly.Python.ORDER_ATOMIC),e=Blockly.Python.valueToCode(a,"user",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"password",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_["import_umqtt.simple"]="from umqtt.simple import MQTTClient";return 0==e.length&&0==a.length?
"mqtt_client = MQTTClient("+b+", server="+c+", port="+d+")\n":"mqtt_client = MQTTClient("+b+", server="+c+", port="+d+", user="+e+", password="+a+")\n"};Blockly.Python.mqtt_add_to_buffer=function(a){var b=Blockly.Python.valueToCode(a,"fieldname",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"value",Blockly.Python.ORDER_ATOMIC);return"mqtt_buffer += ("+b+' + "=" + str('+a+')) if not len(mqtt_buffer) else ("&" + '+b+' + "=" + str('+a+"))\n"};
Blockly.Python.mqtt_publish_buffer=function(a){var b=Blockly.Python.valueToCode(a,"topic",Blockly.Python.ORDER_ATOMIC);a=a.getFieldValue("MQTT_QOS");Blockly.Python.definitions_["import_umqtt.simple"]="from umqtt.simple import MQTTClient";return"mqtt_client.publish("+b+", mqtt_buffer,qos="+a+')\nmqtt_buffer = ""\n'};
Blockly.Python.mqtt_publish_payload=function(a){var b=Blockly.Python.valueToCode(a,"topic",Blockly.Python.ORDER_ATOMIC),c=Blockly.Python.valueToCode(a,"payload",Blockly.Python.ORDER_ATOMIC);a=a.getFieldValue("MQTT_QOS");Blockly.Python.definitions_["import_umqtt.simple"]="from umqtt.simple import MQTTClient";return"mqtt_client.publish("+b+", "+c+", qos="+a+")\n"};
Blockly.Python.mqtt_set_callback=function(a){for(var b=Blockly.Python.variableDB_.getName(a.getFieldValue("MQTT_DATA_VAR"),Blockly.VARIABLE_CATEGORY_NAME),c=Blockly.Python.variableDB_.getName(a.getFieldValue("MQTT_TOPIC_VAR"),Blockly.VARIABLE_CATEGORY_NAME),d=[],e,f=a.workspace,h=Blockly.Variables.allUsedVarModels(f)||[],g=0;e=h[g];g++)e=e.name,-1==a.getVars().indexOf(e)&&e!=b&&e!=c&&d.push(Blockly.Python.variableDB_.getName(e,Blockly.VARIABLE_CATEGORY_NAME));f=Blockly.Variables.allDeveloperVariables(f);
for(g=0;g<f.length;g++)d.push(Blockly.Python.variableDB_.getName(f[g],Blockly.Names.DEVELOPER_VARIABLE_TYPE));d=d.length?Blockly.Python.INDENT+"global "+d.join(", "):"";Blockly.Python.definitions_["import_umqtt.simple"]="from umqtt.simple import MQTTClient";a=Blockly.Python.statementToCode(a,"do");return"mqtt_client.set_callback("+Blockly.Python.provideFunction_("mqtt_callback",["def "+Blockly.Python.FUNCTION_NAME_PLACEHOLDER_+"("+c+","+b+"):",d,Blockly.Python.INDENT+"print("+c+")",a])+")\n"};
Blockly.Python.mqtt_subscribe=function(a){a=Blockly.Python.valueToCode(a,"topic",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_["import_umqtt.simple"]="from umqtt.simple import MQTTClient";return"mqtt_client.subscribe("+a+")\n"};Blockly.Python.mqtt_check_msg=function(a){Blockly.Python.definitions_["import_umqtt.simple"]="from umqtt.simple import MQTTClient";return"mqtt_client.check_msg()\n"};
Blockly.Python.mqtt_wait_msg=function(a){Blockly.Python.definitions_["import_umqtt.simple"]="from umqtt.simple import MQTTClient";return"mqtt_client.wait_msg()\n"};Blockly.Python.mqtt_disconnect=function(a){Blockly.Python.definitions_["import_umqtt.simple"]="from umqtt.simple import MQTTClient";return"mqtt_client.disconnect()\n"};Blockly.Python.mqtt_connect=function(a){Blockly.Python.definitions_["import_umqtt.simple"]="from umqtt.simple import MQTTClient";return"mqtt_client.connect()\n"};
Blockly.Python.machine_unique_id=function(a){Blockly.Python.definitions_.import_machine="import machine";return["machine.unique_id()",Blockly.JavaScript.ORDER_NONE]};Blockly.Python.machine_reset_cause=function(a){Blockly.Python.definitions_.import_machine="import machine";return["machine.reset_cause()",Blockly.JavaScript.ORDER_MEMBER]};
Blockly.Python.ujson_dump=function(a){a=Blockly.Python.valueToCode(a,"pIn",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_ujson="import ujson";return"ujson.dump("+a+")\n"};Blockly.Python.ujson_dumps=function(a){a=Blockly.Python.valueToCode(a,"dic",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_ujson="import ujson";return["ujson.dumps("+a+")",Blockly.JavaScript.ORDER_NONE]};
Blockly.Python.ujson_load=function(a){a=Blockly.Python.valueToCode(a,"pIn",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_ujson="import ujson";return"ujson.load("+a+")\n"};Blockly.Python.ujson_loads=function(a){a=Blockly.Python.valueToCode(a,"json_str",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_ujson="import ujson";return["ujson.loads("+a+")",Blockly.JavaScript.ORDER_NONE]};
Blockly.Python.uos_chdir=function(a){Blockly.Python.definitions_.import_uos="import uos";return"uos.chdir("+Blockly.Python.valueToCode(a,"path",Blockly.Python.ORDER_ATOMIC)+")\n"};Blockly.Python.uos_getcwd=function(a){Blockly.Python.definitions_.import_uos="import uos";return["uos.getcwd()",Blockly.JavaScript.ORDER_NONE]};
Blockly.Python.uos_ilistdir=function(a){Blockly.Python.definitions_.import_uos="import uos";return"uos.ilistdir("+Blockly.Python.valueToCode(a,"path",Blockly.Python.ORDER_ATOMIC)+")\n"};Blockly.Python.uos_listdir=function(a){Blockly.Python.definitions_.import_uos="import uos";return"uos.listdir("+Blockly.Python.valueToCode(a,"path",Blockly.Python.ORDER_ATOMIC)+")\n"};
Blockly.Python.uos_mkdir=function(a){Blockly.Python.definitions_.import_uos="import uos";return"uos.mkdir("+Blockly.Python.valueToCode(a,"path",Blockly.Python.ORDER_ATOMIC)+")\n"};Blockly.Python.uos_remove=function(a){Blockly.Python.definitions_.import_uos="import uos";return"uos.remove("+Blockly.Python.valueToCode(a,"file",Blockly.Python.ORDER_ATOMIC)+")\n"};
Blockly.Python.uos_rmdir=function(a){Blockly.Python.definitions_.import_uos="import uos";return"uos.rmdir("+Blockly.Python.valueToCode(a,"path",Blockly.Python.ORDER_ATOMIC)+")\n"};Blockly.Python.uos_rename=function(a){Blockly.Python.definitions_.import_uos="import uos";var b=Blockly.Python.valueToCode(a,"old_path",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"new_path",Blockly.Python.ORDER_ATOMIC);return"uos.rename("+b+", "+a+")\n"};
Blockly.Python.delay_ms=function(a){a=Blockly.Python.valueToCode(a,"time",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_time="import utime";return"utime.sleep_ms("+a+")\n"};Blockly.Python.delay_us=function(a){a=Blockly.Python.valueToCode(a,"time",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_time="import utime";return"utime.sleep_us("+a+")\n"};Blockly.Python.ticks_ms=function(a){Blockly.Python.definitions_.import_time="import utime";return["utime.ticks_ms()",Blockly.Python.ORDER_NONE]};
Blockly.Python.ticks_diff=function(a){var b=Blockly.Python.valueToCode(a,"start",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"end",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_time="import utime";b=b.split("\n").join("");a=a.split("\n").join("");return["utime.ticks_diff("+a+","+b+")",Blockly.Python.ORDER_NONE]};
Blockly.Python.get_rtc=function(a){Blockly.Python.definitions_.import_rtc="from machine import RTC";Blockly.Python.definitions_.import_rtc_def="rtc = RTC()";return["rtc.datetime()",Blockly.Python.ORDER_NONE]};
Blockly.Python.set_rtc=function(a){var b=Blockly.Python.valueToCode(a,"year",Blockly.Python.ORDER_ATOMIC)||2020,c=Blockly.Python.valueToCode(a,"month",Blockly.Python.ORDER_ATOMIC)||2,d=Blockly.Python.valueToCode(a,"day",Blockly.Python.ORDER_ATOMIC)||1,e=Blockly.Python.valueToCode(a,"hour",Blockly.Python.ORDER_ATOMIC)||12,f=Blockly.Python.valueToCode(a,"minute",Blockly.Python.ORDER_ATOMIC)||0;a=Blockly.Python.valueToCode(a,"second",Blockly.Python.ORDER_ATOMIC)||0;Blockly.Python.definitions_.import_rtc=
"from machine import RTC";Blockly.Python.definitions_.import_rtc_def="rtc = RTC()";return"rtc.datetime(("+b+", "+c+", "+d+", 0, "+e+", "+f+", "+a+", 0))\n"};
Blockly.Python.get_rtc_datetime=function(a){var b=Blockly.Python.valueToCode(a,"year",Blockly.Python.ORDER_ATOMIC)||"_",c=Blockly.Python.valueToCode(a,"month",Blockly.Python.ORDER_ATOMIC)||"_",d=Blockly.Python.valueToCode(a,"day",Blockly.Python.ORDER_ATOMIC)||"_",e=Blockly.Python.valueToCode(a,"hour",Blockly.Python.ORDER_ATOMIC)||"_",f=Blockly.Python.valueToCode(a,"minute",Blockly.Python.ORDER_ATOMIC)||"_";a=Blockly.Python.valueToCode(a,"second",Blockly.Python.ORDER_ATOMIC)||"_";Blockly.Python.definitions_.import_rtc=
"from machine import RTC";Blockly.Python.definitions_.import_rtc_def="rtc = RTC()";return b+","+c+","+d+",_,"+e+","+f+","+a+",_ = rtc.datetime()\n"};Blockly.Python.stop_timer=function(a){Blockly.Python.definitions_.import_timer="from machine import Timer";return"tim"+Blockly.Python.valueToCode(a,"timerNumber",Blockly.Python.ORDER_ATOMIC)+".deinit()\n"};
Blockly.Python.timer=function(a){var b=a.getFieldValue("interval"),c=a.getFieldValue("timerNumber");a=Blockly.Python.statementToCode(a,"statements");Blockly.Python.definitions_.import_timer="from machine import Timer";Blockly.Python.definitions_["import_timer_start"+c]="tim"+c+"=Timer("+c+")";Blockly.Python.definitions_["import_timer_callback"+c]="\n#Timer Function Callback\ndef timerFunc"+c+"(t):\n\t"+a+"\n\n";return"tim"+c+".init(period="+b+", mode=Timer.PERIODIC, callback=timerFunc"+c+")\n"};
Blockly.Python.deep_sleep8266=function(a){a=Blockly.Python.valueToCode(a,"interval",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_machine="import machine";return"rtc = machine.RTC()\nrtc.irq(trigger=rtc.ALARM0, wake=machine.DEEPSLEEP)\nrtc.alarm(rtc.ALARM0, "+(a+")\nmachine.deepsleep()\n")};
Blockly.Python.deep_sleep=function(a){a=Blockly.Python.valueToCode(a,"interval",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_machine="import machine";return"machine.deepsleep("+a+")\n"};Blockly.Python.randomforestclassifier=function(a){a=Blockly.Python.valueToCode(a,"random_state",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_random_forest_classifier="from sklearn.ensemble import RandomForestClassifier";return["RandomForestClassifier(random_state="+a+")\n",Blockly.Python.ORDER_NONE]};
Blockly.Python.fit=function(a){var b=Blockly.Python.valueToCode(a,"classifier",Blockly.Python.ORDER_ATOMIC),c=Blockly.Python.valueToCode(a,"X",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"y",Blockly.Python.ORDER_ATOMIC);return b+".fit("+c+","+a+")\n"};Blockly.Python.predict=function(a){var b=Blockly.Python.valueToCode(a,"classifier",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"X",Blockly.Python.ORDER_ATOMIC);return[b+".predict("+a+")\n",Blockly.Python.ORDER_NONE]};
Blockly.Python.file_open_write=function(a){return"f = open("+Blockly.Python.valueToCode(a,"filename",Blockly.Python.ORDER_ATOMIC)+", 'a+')\n"};Blockly.Python.file_open_read=function(a){return"f = open("+Blockly.Python.valueToCode(a,"filename",Blockly.Python.ORDER_ATOMIC)+")\n"};Blockly.Python.file_close=function(a){Blockly.Python.valueToCode(a,"filename",Blockly.Python.ORDER_ATOMIC);return"f.close()\n"};Blockly.Python.file_read=function(a){return["f.read()",Blockly.Python.ORDER_NONE]};
Blockly.Python.file_write=function(a){return"f.write("+Blockly.Python.valueToCode(a,"data",Blockly.Python.ORDER_ATOMIC)+")\nf.write('\\n')\n"};Blockly.Python.files_list=function(a){Blockly.Python.definitions_.import_uos="import uos";return["uos.listdir()",Blockly.Python.ORDER_NONE]};
Blockly.Python.hcsr_init=function(a){var b=Blockly.Python.valueToCode(a,"echo",Blockly.Python.ORDER_NONE),c=Blockly.Python.valueToCode(a,"trigger",Blockly.Python.ORDER_NONE);a=Blockly.Python.valueToCode(a,"timeout",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_hcr="from hcsr04 import HCSR04";return"hcsr_sensor = HCSR04(trigger_pin="+c+", echo_pin="+b+", echo_timeout_us="+a+")\n"};Blockly.Python.hcsr_read=function(a){return["hcsr_sensor.distance_cm()",Blockly.Python.ORDER_NONE]};
Blockly.Python.char_lcd_init=function(a){var b=Blockly.Python.valueToCode(a,"sda",Blockly.Python.ORDER_NONE),c=Blockly.Python.valueToCode(a,"scl",Blockly.Python.ORDER_NONE),d=Blockly.Python.valueToCode(a,"lines",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"columns",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_i2c="from machine import I2C";Blockly.Python.definitions_.import_pin="from machine import Pin";Blockly.Python.definitions_.import_i2c_lcd="from esp8266_i2c_lcd import I2cLcd";
return"DEFAULT_I2C_ADDR = 0x27\ni2c = I2C(scl=Pin("+c+"), sda=Pin("+b+"), freq=400000)\nlcd = I2cLcd(i2c, DEFAULT_I2C_ADDR, "+d+", "+a+")\n"};Blockly.Python.char_lcd_clear=function(a){return"lcd.clear()\n"};Blockly.Python.char_lcd_putstr=function(a){return"lcd.putstr("+Blockly.Python.valueToCode(a,"text",Blockly.Python.ORDER_ATOMIC)+")\n"};
Blockly.Python.char_lcd_moveto=function(a){var b=Blockly.Python.valueToCode(a,"x",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"y",Blockly.Python.ORDER_ATOMIC);return"lcd.move_to(int("+b+"), int("+a+"))\n"};Blockly.Python.char_lcd_backlight=function(a){return"True"==Blockly.Python.valueToCode(a,"state",Blockly.Python.ORDER_ATOMIC)?"lcd.backlight_on()\n":"lcd.backlight_off()\n"};
Blockly.Python.char_lcd_display=function(a){return"True"==Blockly.Python.valueToCode(a,"state",Blockly.Python.ORDER_ATOMIC)?"lcd.display_on()\n":"lcd.display_off()\n"};
Blockly.Python.rfid_rc522_init=function(a){var b=Blockly.Python.valueToCode(a,"sck",Blockly.Python.ORDER_NONE),c=Blockly.Python.valueToCode(a,"mosi",Blockly.Python.ORDER_NONE),d=Blockly.Python.valueToCode(a,"miso",Blockly.Python.ORDER_NONE),e=Blockly.Python.valueToCode(a,"rst",Blockly.Python.ORDER_NONE);a=Blockly.Python.valueToCode(a,"sda",Blockly.Python.ORDER_NONE);Blockly.Python.definitions_.import_mfrc522="import mfrc522";return"rfid = mfrc522.MFRC522("+b+", "+c+", "+d+", "+e+", "+a+")\n"};
Blockly.Python.rfid_rc522_detect_card=function(a){var b=Blockly.Python.valueToCode(a,"stat",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"tag",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_mfrc522="import mfrc522";return"("+b+", "+a+") = rfid.request(rfid.REQIDL)\n"};Blockly.Python.rfid_rc522_ok=function(a){return["rfid.OK",Blockly.Python.ORDER_MEMBER]};
Blockly.Python.rfid_rc522_anticoll=function(a){var b=Blockly.Python.valueToCode(a,"stat",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"tag",Blockly.Python.ORDER_ATOMIC);return"("+b+", "+a+") = rfid.anticoll()\n"};Blockly.Python.rfid_rc522_get_uid_string=function(a){a=Blockly.Python.valueToCode(a,"obj",Blockly.Python.ORDER_ATOMIC);return['"%02x%02x%02x%02x" % ('+a+"[0], "+a+"[1], "+a+"[2], "+a+"[3])",Blockly.Python.ORDER_MEMBER]};Blockly.Python.rfid_rc522_read_card=function(a){return"rfid = mfrc522.MFRC522(0,2,4,5,14)\n"};
Blockly.Python.rfid_rc522_write_card=function(a){return"rfid = mfrc522.MFRC522(0,2,4,5,14)\n"};
Blockly.Python.net_ntp_sync=function(a){a=Blockly.Python.valueToCode(a,"tz",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_ntptime="import ntptime";Blockly.Python.definitions_.import_rtc="from machine import RTC";Blockly.Python.definitions_.import_utime="import utime";Blockly.Python.definitions_.import_rtc_def="rtc = RTC()";a="ntptime.settime()\nutc_shift="+(a+"\ntm = utime.localtime(utime.mktime(utime.localtime()) + utc_shift*3600)\ntm = tm[0:3] + (0,) + tm[3:6] + (0,)\n");return a+=
"rtc.datetime(tm)\n"};
Blockly.Python.net_get_ntp=function(a){var b=Blockly.Python.valueToCode(a,"year",Blockly.Python.ORDER_ATOMIC)||"_",c=Blockly.Python.valueToCode(a,"month",Blockly.Python.ORDER_ATOMIC)||"_",d=Blockly.Python.valueToCode(a,"day",Blockly.Python.ORDER_ATOMIC)||"_",e=Blockly.Python.valueToCode(a,"hour",Blockly.Python.ORDER_ATOMIC)||"_",f=Blockly.Python.valueToCode(a,"minute",Blockly.Python.ORDER_ATOMIC)||"_";a=Blockly.Python.valueToCode(a,"second",Blockly.Python.ORDER_ATOMIC)||"_";Blockly.Python.definitions_.import_utime=
"import utime";return b+","+c+","+d+","+e+","+f+","+a+",_,_ = utime.localtime()\n"};Blockly.Python.net_socket_connect=function(a){var b=Blockly.Python.valueToCode(a,"host",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"port",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_socket="import socket";b="addr_info = socket.getaddrinfo("+b+", "+a+")\naddr = addr_info[0][-1]\ns = socket.socket()\n";return b+="s.connect(addr)\n"};
Blockly.Python.net_socket_receive=function(a){return["str(s.recv("+Blockly.Python.valueToCode(a,"bytes",Blockly.Python.ORDER_ATOMIC)+"), 'utf8')",Blockly.Python.ORDER_NONE]};Blockly.Python.net_socket_send=function(a){return"s.send(bytes("+Blockly.Python.valueToCode(a,"bytes",Blockly.Python.ORDER_ATOMIC)+", 'utf8'))\n"};Blockly.Python.net_socket_close=function(a){return"s.close()\n"};
Blockly.Python.net_http_server_begin=function(a){a=Blockly.Python.valueToCode(a,"port",Blockly.Python.ORDER_NONE);Blockly.Python.definitions_.import_webserver="import ESP8266WebServer";return"ESP8266WebServer.begin("+a+")\n"};
Blockly.Python.net_http_on_path=function(a){for(var b=Blockly.Python.valueToCode(a,"path",Blockly.Python.ORDER_NONE),c=Blockly.Python.valueToCode(a,"callback",Blockly.Python.ORDER_NONE),d=[],e,f=a.workspace,h=Blockly.Variables.allUsedVarModels(f)||[],g=0;e=h[g];g++)e=e.name,-1==a.getVars().indexOf(e)&&d.push(Blockly.Python.variableDB_.getName(e,Blockly.VARIABLE_CATEGORY_NAME));f=Blockly.Variables.allDeveloperVariables(f);for(g=0;g<f.length;g++)d.push(Blockly.Python.variableDB_.getName(f[g],Blockly.Names.DEVELOPER_VARIABLE_TYPE));
d=d.length?Blockly.Python.INDENT+"global "+d.join(", "):"";Blockly.Python.definitions_.import_webserver="import ESP8266WebServer";a=Blockly.Python.statementToCode(a,"do");0==a.length&&(a=Blockly.Python.INDENT+"pass\n");Blockly.Python.provideFunction_(c,["def "+c.replace(/^'/,"").replace(/'$/,"")+"(socket, args):",d,a]);return"ESP8266WebServer.onPath("+b+", "+c+")\n"};
Blockly.Python.net_http_server_in_args=function(a){return[Blockly.Python.valueToCode(a,"key",Blockly.Python.ORDER_NONE)+" in args",Blockly.Python.ORDER_NONE]};Blockly.Python.net_http_server_get_args_value=function(a){return["args["+Blockly.Python.valueToCode(a,"key",Blockly.Python.ORDER_NONE)+"]",Blockly.Python.ORDER_MEMBER]};
Blockly.Python.net_http_server_send_response_ok=function(a){var b=Blockly.Python.valueToCode(a,"status",Blockly.Python.ORDER_NONE),c=Blockly.Python.valueToCode(a,"content",Blockly.Python.ORDER_NONE);a=Blockly.Python.valueToCode(a,"mime",Blockly.Python.ORDER_NONE);Blockly.Python.definitions_.import_webserver="import ESP8266WebServer";return"ESP8266WebServer.ok(socket, '"+b+"', "+c+", "+a+")\n"};
Blockly.Python.net_http_server_send_response_error=function(a){var b=Blockly.Python.valueToCode(a,"status",Blockly.Python.ORDER_NONE);a=Blockly.Python.valueToCode(a,"content",Blockly.Python.ORDER_NONE);Blockly.Python.definitions_.import_webserver="import ESP8266WebServer";return"ESP8266WebServer.err(socket, '"+b+"', "+a+")\n"};Blockly.Python.net_http_server_start=function(a){Blockly.Python.definitions_.import_webserver="import ESP8266WebServer";return"try:\n  while True:\n    ESP8266WebServer.handleClient()\nexcept:\n  ESP8266WebServer.close()\n"};
Blockly.Python.net_http_server_setdocpath=function(a){a=Blockly.Python.valueToCode(a,"path",Blockly.Python.ORDER_NONE);Blockly.Python.definitions_.import_webserver="import ESP8266WebServer";return"ESP8266WebServer.setDocPath("+a+")\n"};Blockly.Python.net_http_server_settpldata=function(a){a=Blockly.Python.valueToCode(a,"data",Blockly.Python.ORDER_NONE);Blockly.Python.definitions_.import_webserver="import ESP8266WebServer";return"ESP8266WebServer.setTplData("+a+")\n"};
Blockly.Python.stepper_init=function(a){var b=Blockly.Python.valueToCode(a,"p0",Blockly.Python.ORDER_NONE),c=Blockly.Python.valueToCode(a,"p1",Blockly.Python.ORDER_NONE),d=Blockly.Python.valueToCode(a,"p2",Blockly.Python.ORDER_NONE);a=Blockly.Python.valueToCode(a,"p3",Blockly.Python.ORDER_NONE);Blockly.Python.definitions_.import_machine="import machine";Blockly.Python.definitions_.import_time="import utime";return"\npins = [\n    machine.Pin("+b+", machine.Pin.OUT),  # 1\n    machine.Pin("+c+", machine.Pin.OUT),  # 2\n    machine.Pin("+
d+", machine.Pin.OUT),  # 4\n    machine.Pin("+a+", machine.Pin.OUT),  # 8\n]\n\nphases = [ 1, 5, 4, 6, 2, 10, 8, 9 ]\n"};Blockly.Python.stepper_step=function(a){return"\nfor i in range(1, "+Blockly.Python.valueToCode(a,"steps",Blockly.Python.ORDER_ATOMIC)+"):\n    for phase in phases:\n        for n, p in enumerate(pins):\n            pins[n](phase & 1 < < n)\n        time.sleep(0.001)\n"};
Blockly.Python.dc_motor_init=function(a){var b=Blockly.Python.valueToCode(a,"pwm",Blockly.Python.ORDER_NONE),c=Blockly.Python.valueToCode(a,"dir1",Blockly.Python.ORDER_NONE);a=Blockly.Python.valueToCode(a,"dir2",Blockly.Python.ORDER_NONE);Blockly.Python.definitions_.import_pin="from machine import Pin";return b="dc_motor_pin_a = machine.Pin("+c+", machine.Pin.OUT)\ndc_motor_pin_b = machine.Pin("+(a+", machine.Pin.OUT)\ndc_motor_pwm = machine.PWM(")+(b+")\n")};
Blockly.Python.dc_motor_power=function(a){return"dc_motor_pwm.duty("+Blockly.Python.valueToCode(a,"power",Blockly.Python.ORDER_ATOMIC)+")\n"};
Blockly.Python.dc_motor_direction=function(a){a=Blockly.Python.valueToCode(a,"dir",Blockly.Python.ORDER_ATOMIC);var b="";0==a&&(b="dc_motor_pin_a.value=0\ndc_motor_pin_b.value=0\n");1==a&&(b="dc_motor_pin_a.value=1\ndc_motor_pin_b.value=0\n");2==a&&(b="dc_motor_pin_a.value=0\ndc_motor_pin_b.value=1\n");3==a&&(b="dc_motor_pin_a.value=1\ndc_motor_pin_b.value=1\n");return b};Blockly.Python.dc_motor_stop=function(a){return"dc_motor_pin_a.value=0\ndc_motor_pin_b.value=0\n"};
Blockly.Python.esp32_can_init=function(a){Blockly.Python.valueToCode(a,"mode",Blockly.Python.ORDER_ATOMIC);Blockly.Python.valueToCode(a,"baudrate",Blockly.Python.ORDER_ATOMIC);Blockly.Python.valueToCode(a,"extframe",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_can="from machine import CAN";return"can = CAN(0, extframe=True, mode=CAN.LOOPBACK, baudrate=500)\n"};Blockly.Python.esp32_can_filter=function(a){Blockly.Python.valueToCode(a,"filter",Blockly.Python.ORDER_ATOMIC);return"can.setfilter(0, CAN.FILTER_ADDRESS, [0x102, 0]) \n"};
Blockly.Python.esp32_can_send=function(a){Blockly.Python.valueToCode(a,"id",Blockly.Python.ORDER_ATOMIC);Blockly.Python.valueToCode(a,"data",Blockly.Python.ORDER_ATOMIC);return"can.send([1,2,3], 0x102) \n"};Blockly.Python.esp32_can_recv=function(a){return["can.recv()",Blockly.Python.ORDER_NONE]};Blockly.Python.python_try_catch=function(a){var b=Blockly.Python.statementToCode(a,"try");a=Blockly.Python.statementToCode(a,"catch");return"try:\n"+b+"except:\n"+a+"\n"};
Blockly.Python.xtools_get_id=function(a){Blockly.Python.definitions_.import_xtools="import xtools";return["xtools.get_id()",Blockly.JavaScript.ORDER_NONE]};Blockly.Python.xtools_get_num=function(a){a=Blockly.Python.valueToCode(a,"text_str",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_xtools="import xtools";return["xtools.get_num("+a+")",Blockly.JavaScript.ORDER_NONE]};
Blockly.Python.xtools_random_in_range=function(a){var b=Blockly.Python.valueToCode(a,"low",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"high",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_xtools="import xtools";return["xtools.random_in_range("+b+", "+a+")",Blockly.JavaScript.ORDER_NONE]};
Blockly.Python.xtools_map_range=function(a){var b=Blockly.Python.valueToCode(a,"in_min",Blockly.Python.ORDER_ATOMIC),c=Blockly.Python.valueToCode(a,"in_max",Blockly.Python.ORDER_ATOMIC),d=Blockly.Python.valueToCode(a,"out_min",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"out_max",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_xtools="import xtools";return["xtools.map_range("+b+", "+c+", "+d+", "+a+")",Blockly.JavaScript.ORDER_NONE]};
Blockly.Python.xtools_connect_wifi=function(a){var b=Blockly.Python.valueToCode(a,"ssid",Blockly.Python.ORDER_ATOMIC),c=Blockly.Python.valueToCode(a,"pwd",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"timeout",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_xtools="import xtools";return"xtools.connect_wifi_led("+b+", "+c+", "+a+")\n"};
Blockly.Python.xtools_connect_wifi_ip=function(a){var b=Blockly.Python.valueToCode(a,"ssid",Blockly.Python.ORDER_ATOMIC),c=Blockly.Python.valueToCode(a,"pwd",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"timeout",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_xtools="import xtools";return["xtools.connect_wifi_led("+b+", "+c+", "+a+")",Blockly.JavaScript.ORDER_NONE]};
Blockly.Python.xtools_webhook_post=function(a){var b=Blockly.Python.valueToCode(a,"URL",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"json",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_xtools="import xtools";return"xtools.webhook_post("+b+", "+a+")\n"};Blockly.Python.xtools_webhook_get=function(a){a=Blockly.Python.valueToCode(a,"URL",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_xtools="import xtools";return"xtools.webhook_get("+a+")\n"};
Blockly.Python.xtools_line_msg=function(a){var b=Blockly.Python.valueToCode(a,"token",Blockly.Python.ORDER_ATOMIC);a=Blockly.Python.valueToCode(a,"message",Blockly.Python.ORDER_ATOMIC);Blockly.Python.definitions_.import_xtools="import xtools";return"xtools.line_msg("+b+", "+a+")\n"};